SET SERVEROUTPUT ON;

DROP TABLE PILOT_CURSA_F1;
DROP TABLE ECHIPA_SPONSOR_F1;
DROP TABLE BILET_F1;
DROP TABLE CURSA_F1;
DROP TABLE VEHICUL_F1;
DROP TABLE ISTORIC_ECHIPA_PILOT_F1;
DROP TABLE PILOT_F1;
DROP TABLE ECHIPA_F1;
DROP TABLE TIP_BILET_F1;
DROP TABLE CIRCUIT_F1;
DROP TABLE MODEL_VEHICUL_F1;
DROP TABLE SPONSOR_F1;



DROP SEQUENCE tip_bilet_seq;
DROP SEQUENCE pilot_seq;
DROP SEQUENCE echipa_seq;
DROP SEQUENCE circuit_seq;
DROP SEQUENCE contract_seq;


CREATE SEQUENCE tip_bilet_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE pilot_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE echipa_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE circuit_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE contract_seq START WITH 101 INCREMENT BY 1;


CREATE TABLE SPONSOR_F1 (
    id_sponsor INT PRIMARY KEY,
    nume VARCHAR(100) NOT NULL,
    tip_parteneriat VARCHAR(50),
    domeniu VARCHAR(50)
);


CREATE TABLE MODEL_VEHICUL_F1 (
    id_model INT PRIMARY KEY,
    nume VARCHAR(100),
    aerodinamica VARCHAR(50),
    viteza_maxima INT 
);


CREATE TABLE CIRCUIT_F1 (
    id_circuit INT PRIMARY KEY,
    nume VARCHAR(100) NOT NULL,
    tara VARCHAR(50),
    oras VARCHAR(50),
    lungime DECIMAL(5, 3), 
    viraje INT,
    drs_zone INT
);


CREATE TABLE TIP_BILET_F1 (
    id_tip_bilet INT PRIMARY KEY,
    categorie VARCHAR(50) CHECK (categorie IN ('Bronze', 'Silver', 'Gold', 'Platinum', 'VIP', 'Exclusive')),
    acces_pitstop CHAR(3) CHECK (acces_pitstop IN ('YES', 'NO'))
);


CREATE TABLE ECHIPA_F1 (
    id_echipa INT PRIMARY KEY,
    nume VARCHAR(100) NOT NULL,
    sediu VARCHAR(100),
    buget DECIMAL(15, 2),
    an_infiintare INT
);


CREATE TABLE PILOT_F1 (
    id_pilot INT PRIMARY KEY,
    nume VARCHAR(50),
    prenume VARCHAR(50),
    data_nastere DATE,
    nationalitate VARCHAR(50),
    puncte INT DEFAULT 0,
    titluri INT DEFAULT 0
);


CREATE TABLE VEHICUL_F1 (
    id_vehicul INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    id_echipa INT NOT NULL, 
    id_model INT NOT NULL, 
    greutate INT, 
    pneuri VARCHAR(50), 
    pret DECIMAL(15, 2),
    data_inspectie DATE,
    
    FOREIGN KEY (id_echipa) REFERENCES ECHIPA_F1(id_echipa),
    FOREIGN KEY (id_model) REFERENCES MODEL_VEHICUL_F1(id_model)
);


CREATE TABLE CURSA_F1 (
    id_cursa INT PRIMARY KEY,
    id_circuit INT NOT NULL, 
    tip_cursa VARCHAR(50) CHECK (tip_cursa IN ('Grand Prix', 'Sprint Race', 'Practice Session', 'Qualifying')),
    data_cursa DATE,
    durata INT, 
    record_timp VARCHAR(20),
    vreme VARCHAR(50),
    status VARCHAR(20) CHECK (status IN ('In Progress', 'Cancelled', 'Suspended', 'Finished', 'Planned')),
    
    FOREIGN KEY (id_circuit) REFERENCES CIRCUIT_F1(id_circuit)
);


CREATE TABLE BILET_F1 (
    id_bilet INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cursa INT NOT NULL,
    id_tip_bilet INT NOT NULL,
    loc_tribuna VARCHAR(10),
    loc_rand INT,
    loc_numar INT,
    data_achizitie DATE,
    stare VARCHAR(20) CHECK (stare IN ('SOLD', 'VALID')),
    
    FOREIGN KEY (id_cursa) REFERENCES CURSA_F1(id_cursa),
    FOREIGN KEY (id_tip_bilet) REFERENCES TIP_BILET_F1(id_tip_bilet)
);


CREATE TABLE ECHIPA_SPONSOR_F1 (
    id_echipa INT,
    id_sponsor INT,
    PRIMARY KEY (id_echipa, id_sponsor),
    contributie_financiara DECIMAL(15, 2),
    status_activ VARCHAR2(3) CHECK (status_activ IN ('YES', 'NO')),
    
    FOREIGN KEY (id_echipa) REFERENCES ECHIPA_F1(id_echipa),
    FOREIGN KEY (id_sponsor) REFERENCES SPONSOR_F1(id_sponsor)
);


CREATE TABLE PILOT_CURSA_F1 (
    id_pilot INT,
    id_cursa INT,
    PRIMARY KEY (id_pilot, id_cursa),
    pozitie_start INT,
    pozitie_finala INT,
    
    FOREIGN KEY (id_pilot) REFERENCES PILOT_F1(id_pilot),
    FOREIGN KEY (id_cursa) REFERENCES CURSA_F1(id_cursa)
);


CREATE TABLE ISTORIC_ECHIPA_PILOT_F1 (
    id_contract INT PRIMARY KEY,
    id_echipa INT NOT NULL,
    id_pilot INT NOT NULL,
    
    data_inceput DATE NOT NULL,
    data_final DATE NOT NULL,
    salariu DECIMAL(15, 2),
    
    FOREIGN KEY (id_echipa) REFERENCES ECHIPA_F1(id_echipa),
    FOREIGN KEY (id_pilot) REFERENCES PILOT_F1(id_pilot)
);


-------------------------------------------------------------------------------------------


INSERT INTO SPONSOR_F1 VALUES (1, 'Oracle', 'Title', 'Tech');
INSERT INTO SPONSOR_F1 VALUES (2, 'Petronas', 'Title', 'Energy');
INSERT INTO SPONSOR_F1 VALUES (3, 'Shell', 'Technical', 'Fuel');
INSERT INTO SPONSOR_F1 VALUES (4, 'Aramco', 'Strategic', 'Energy');
INSERT INTO SPONSOR_F1 VALUES (5, 'Google', 'Major', 'Tech');
INSERT INTO SPONSOR_F1 VALUES (6, 'BWT', 'Title', 'Water');
INSERT INTO SPONSOR_F1 VALUES (7, 'HP', 'Title', 'Tech');
INSERT INTO SPONSOR_F1 VALUES (8, 'Rolex', 'Global', 'Luxury');
INSERT INTO SPONSOR_F1 VALUES (9, 'Stake', 'Title', 'Betting');
INSERT INTO SPONSOR_F1 VALUES (10, 'MoneyGram', 'Title', 'Finance');

select * from sponsor_f1;


INSERT INTO MODEL_VEHICUL_F1 VALUES (1, 'RB20', 'High Downforce', 350);
INSERT INTO MODEL_VEHICUL_F1 VALUES (2, 'W15', 'Balanced', 345);
INSERT INTO MODEL_VEHICUL_F1 VALUES (3, 'SF-24', 'High Speed Cornering', 348);
INSERT INTO MODEL_VEHICUL_F1 VALUES (4, 'MCL38', 'Efficient Drag', 346);
INSERT INTO MODEL_VEHICUL_F1 VALUES (5, 'AMR24', 'Medium Downforce', 342);
INSERT INTO MODEL_VEHICUL_F1 VALUES (6, 'A524', 'Low Drag', 340);
INSERT INTO MODEL_VEHICUL_F1 VALUES (7, 'FW46', 'Straight Line Speed', 352);
INSERT INTO MODEL_VEHICUL_F1 VALUES (8, 'VCARB 01', 'Technical', 338);
INSERT INTO MODEL_VEHICUL_F1 VALUES (9, 'C44', 'Balanced', 335);
INSERT INTO MODEL_VEHICUL_F1 VALUES (10, 'VF-24', 'Cornering', 330);

select * from model_vehicul_f1;


INSERT INTO CIRCUIT_F1 VALUES (circuit_seq.NEXTVAL, 'Sakhir', 'Bahrain', 'Sakhir', 5.412, 15, 3);
INSERT INTO CIRCUIT_F1 VALUES (circuit_seq.NEXTVAL, 'Jeddah', 'Saudi Arabia', 'Jeddah', 6.174, 27, 3);
INSERT INTO CIRCUIT_F1 VALUES (circuit_seq.NEXTVAL, 'Albert Park', 'Australia', 'Melbourne', 5.278, 14, 4);
INSERT INTO CIRCUIT_F1 VALUES (circuit_seq.NEXTVAL, 'Suzuka', 'Japan', 'Suzuka', 5.807, 18, 1);
INSERT INTO CIRCUIT_F1 VALUES (circuit_seq.NEXTVAL, 'Shanghai', 'China', 'Shanghai', 5.451, 16, 2);
INSERT INTO CIRCUIT_F1 VALUES (circuit_seq.NEXTVAL, 'Miami', 'USA', 'Miami', 5.412, 19, 3);
INSERT INTO CIRCUIT_F1 VALUES (circuit_seq.NEXTVAL, 'Imola', 'Italy', 'Imola', 4.909, 19, 1);
INSERT INTO CIRCUIT_F1 VALUES (circuit_seq.NEXTVAL, 'Monaco', 'Monaco', 'Monte Carlo', 3.337, 19, 1);
INSERT INTO CIRCUIT_F1 VALUES (circuit_seq.NEXTVAL, 'Montreal', 'Canada', 'Montreal', 4.361, 14, 2);
INSERT INTO CIRCUIT_F1 VALUES (circuit_seq.NEXTVAL, 'Catalunya', 'Spain', 'Barcelona', 4.657, 14, 2);

select * from circuit_f1;

INSERT INTO TIP_BILET_F1 VALUES (tip_bilet_seq.NEXTVAL, 'Bronze', 'NO');
INSERT INTO TIP_BILET_F1 VALUES (tip_bilet_seq.NEXTVAL, 'Silver', 'NO');
INSERT INTO TIP_BILET_F1 VALUES (tip_bilet_seq.NEXTVAL, 'Gold', 'NO');
INSERT INTO TIP_BILET_F1 VALUES (tip_bilet_seq.NEXTVAL, 'Platinum', 'NO');
INSERT INTO TIP_BILET_F1 VALUES (tip_bilet_seq.NEXTVAL, 'VIP', 'YES');
INSERT INTO TIP_BILET_F1 VALUES (tip_bilet_seq.NEXTVAL, 'Exclusive', 'YES');

select * from tip_bilet_f1;


INSERT INTO ECHIPA_F1 VALUES (echipa_seq.NEXTVAL, 'Red Bull', 'UK', 600000000, 2005);
INSERT INTO ECHIPA_F1 VALUES (echipa_seq.NEXTVAL, 'Ferrari', 'Italy', 650000000, 1929);
INSERT INTO ECHIPA_F1 VALUES (echipa_seq.NEXTVAL, 'Mercedes', 'UK', 550000000, 2010);
INSERT INTO ECHIPA_F1 VALUES (echipa_seq.NEXTVAL, 'McLaren', 'UK', 450000000, 1963);
INSERT INTO ECHIPA_F1 VALUES (echipa_seq.NEXTVAL, 'Aston Martin', 'UK', 400000000, 2021);
INSERT INTO ECHIPA_F1 VALUES (echipa_seq.NEXTVAL, 'Alpine', 'UK', 350000000, 2021);
INSERT INTO ECHIPA_F1 VALUES (echipa_seq.NEXTVAL, 'Williams', 'UK', 250000000, 1977);
INSERT INTO ECHIPA_F1 VALUES (echipa_seq.NEXTVAL, 'Racing Bulls', 'Italy', 200000000, 2024);
INSERT INTO ECHIPA_F1 VALUES (echipa_seq.NEXTVAL, 'Sauber', 'Switzerland', 180000000, 1993);
INSERT INTO ECHIPA_F1 VALUES (echipa_seq.NEXTVAL, 'Haas', 'USA', 150000000, 2016);

select * from echipa_f1;


INSERT INTO PILOT_F1 VALUES (pilot_seq.NEXTVAL, 'Verstappen', 'Max', TO_DATE('1990-01-26', 'YYYY-MM-DD'), 'NED', 2500, 3);
INSERT INTO PILOT_F1 VALUES (pilot_seq.NEXTVAL, 'Perez', 'Sergio', TO_DATE('1990-01-26', 'YYYY-MM-DD'), 'MEX', 1500, 0);
INSERT INTO PILOT_F1 VALUES (pilot_seq.NEXTVAL, 'Leclerc', 'Charles', TO_DATE('1997-10-16', 'YYYY-MM-DD'), 'MON', 1100, 0);
INSERT INTO PILOT_F1 VALUES (pilot_seq.NEXTVAL, 'Sainz', 'Carlos', TO_DATE('1994-09-01', 'YYYY-MM-DD'), 'ESP', 1000, 0);
INSERT INTO PILOT_F1 VALUES (pilot_seq.NEXTVAL, 'Hamilton', 'Lewis', TO_DATE('1985-01-07', 'YYYY-MM-DD'), 'GBR', 4639, 7);
INSERT INTO PILOT_F1 VALUES (pilot_seq.NEXTVAL, 'Russell', 'George', TO_DATE('1998-02-15', 'YYYY-MM-DD'), 'GBR', 494, 0);
INSERT INTO PILOT_F1 VALUES (pilot_seq.NEXTVAL, 'Norris', 'Lando', TO_DATE('1999-11-13', 'YYYY-MM-DD'), 'GBR', 691, 0);
INSERT INTO PILOT_F1 VALUES (pilot_seq.NEXTVAL, 'Piastri', 'Oscar', TO_DATE('2001-04-06', 'YYYY-MM-DD'), 'AUS', 120, 0);
INSERT INTO PILOT_F1 VALUES (pilot_seq.NEXTVAL, 'Alonso', 'Fernando', TO_DATE('1981-07-29', 'YYYY-MM-DD'), 'ESP', 2280, 2);
INSERT INTO PILOT_F1 VALUES (pilot_seq.NEXTVAL, 'Stroll', 'Lance', TO_DATE('1998-10-29', 'YYYY-MM-DD'), 'CAN', 280, 0);
INSERT INTO PILOT_F1 VALUES (pilot_seq.NEXTVAL, 'Gasly', 'Pierre', TO_DATE('1996-02-07', 'YYYY-MM-DD'), 'FRA', 400, 0);
INSERT INTO PILOT_F1 VALUES (pilot_seq.NEXTVAL, 'Ocon', 'Esteban', TO_DATE('1996-09-17', 'YYYY-MM-DD'), 'FRA', 430, 0);
INSERT INTO PILOT_F1 VALUES (pilot_seq.NEXTVAL, 'Albon', 'Alexander', TO_DATE('1996-03-23', 'YYYY-MM-DD'), 'THA', 240, 0);
INSERT INTO PILOT_F1 VALUES (pilot_seq.NEXTVAL, 'Sargeant', 'Logan', TO_DATE('2000-12-31', 'YYYY-MM-DD'), 'USA', 1, 0);
INSERT INTO PILOT_F1 VALUES (pilot_seq.NEXTVAL, 'Ricciardo', 'Daniel', TO_DATE('1989-07-01', 'YYYY-MM-DD'), 'AUS', 1320, 0);
INSERT INTO PILOT_F1 VALUES (pilot_seq.NEXTVAL, 'Tsunoda', 'Yuki', TO_DATE('2000-05-11', 'YYYY-MM-DD'), 'JPN', 70, 0);
INSERT INTO PILOT_F1 VALUES (pilot_seq.NEXTVAL, 'Bottas', 'Valtteri', TO_DATE('1989-08-28', 'YYYY-MM-DD'), 'FIN', 1797, 0);
INSERT INTO PILOT_F1 VALUES (pilot_seq.NEXTVAL, 'Zhou', 'Guanyu', TO_DATE('1999-05-30', 'YYYY-MM-DD'), 'CHN', 12, 0);
INSERT INTO PILOT_F1 VALUES (pilot_seq.NEXTVAL, 'Hulkenberg', 'Nico', TO_DATE('1987-08-19', 'YYYY-MM-DD'), 'GER', 540, 0);
INSERT INTO PILOT_F1 VALUES (pilot_seq.NEXTVAL, 'Magnussen', 'Kevin', TO_DATE('1992-10-05', 'YYYY-MM-DD'), 'DEN', 190, 0);

select * from pilot_f1;


INSERT INTO ISTORIC_ECHIPA_PILOT_F1 VALUES (contract_seq.NEXTVAL, 1, 1,  TO_DATE('2025-01-01', 'YYYY-MM-DD'), TO_DATE('2029-01-01', 'YYYY-MM-DD'), 48200000);
INSERT INTO ISTORIC_ECHIPA_PILOT_F1 VALUES (contract_seq.NEXTVAL, 1, 2,  TO_DATE('2025-01-04', 'YYYY-MM-DD'), TO_DATE('2029-01-04', 'YYYY-MM-DD'), 15700000);
INSERT INTO ISTORIC_ECHIPA_PILOT_F1 VALUES (contract_seq.NEXTVAL, 2, 5,  TO_DATE('2025-01-08', 'YYYY-MM-DD'), TO_DATE('2028-01-08', 'YYYY-MM-DD'), 39100000);
INSERT INTO ISTORIC_ECHIPA_PILOT_F1 VALUES (contract_seq.NEXTVAL, 2, 6,  TO_DATE('2025-01-11', 'YYYY-MM-DD'), TO_DATE('2029-01-11', 'YYYY-MM-DD'), 7200000);
INSERT INTO ISTORIC_ECHIPA_PILOT_F1 VALUES (contract_seq.NEXTVAL, 3, 3,  TO_DATE('2025-01-15', 'YYYY-MM-DD'), TO_DATE('2029-01-15', 'YYYY-MM-DD'), 26400000);
INSERT INTO ISTORIC_ECHIPA_PILOT_F1 VALUES (contract_seq.NEXTVAL, 3, 4,  TO_DATE('2025-01-18', 'YYYY-MM-DD'), TO_DATE('2028-01-18', 'YYYY-MM-DD'), 13200000);
INSERT INTO ISTORIC_ECHIPA_PILOT_F1 VALUES (contract_seq.NEXTVAL, 4, 7,  TO_DATE('2025-01-22', 'YYYY-MM-DD'), TO_DATE('2028-01-22', 'YYYY-MM-DD'), 21800000);
INSERT INTO ISTORIC_ECHIPA_PILOT_F1 VALUES (contract_seq.NEXTVAL, 4, 8,  TO_DATE('2025-01-25', 'YYYY-MM-DD'), TO_DATE('2029-01-25', 'YYYY-MM-DD'), 5800000);
INSERT INTO ISTORIC_ECHIPA_PILOT_F1 VALUES (contract_seq.NEXTVAL, 5, 9,  TO_DATE('2025-01-29', 'YYYY-MM-DD'), TO_DATE('2029-01-29', 'YYYY-MM-DD'), 19400000);
INSERT INTO ISTORIC_ECHIPA_PILOT_F1 VALUES (contract_seq.NEXTVAL, 5, 10, TO_DATE('2025-02-01', 'YYYY-MM-DD'), TO_DATE('2028-02-01', 'YYYY-MM-DD'), 3000000);
INSERT INTO ISTORIC_ECHIPA_PILOT_F1 VALUES (contract_seq.NEXTVAL, 6, 11, TO_DATE('2025-02-05', 'YYYY-MM-DD'), TO_DATE('2029-02-05', 'YYYY-MM-DD'), 5300000);
INSERT INTO ISTORIC_ECHIPA_PILOT_F1 VALUES (contract_seq.NEXTVAL, 6, 12, TO_DATE('2025-02-08', 'YYYY-MM-DD'), TO_DATE('2028-02-08', 'YYYY-MM-DD'), 7400000);
INSERT INTO ISTORIC_ECHIPA_PILOT_F1 VALUES (contract_seq.NEXTVAL, 7, 13, TO_DATE('2025-02-12', 'YYYY-MM-DD'), TO_DATE('2028-02-12', 'YYYY-MM-DD'), 4200000);
INSERT INTO ISTORIC_ECHIPA_PILOT_F1 VALUES (contract_seq.NEXTVAL, 7, 14, TO_DATE('2025-02-15', 'YYYY-MM-DD'), TO_DATE('2029-02-15', 'YYYY-MM-DD'), 1900000);
INSERT INTO ISTORIC_ECHIPA_PILOT_F1 VALUES (contract_seq.NEXTVAL, 8, 15, TO_DATE('2025-02-19', 'YYYY-MM-DD'), TO_DATE('2028-02-19', 'YYYY-MM-DD'), 8600000);
INSERT INTO ISTORIC_ECHIPA_PILOT_F1 VALUES (contract_seq.NEXTVAL, 8, 16, TO_DATE('2025-02-22', 'YYYY-MM-DD'), TO_DATE('2029-02-22', 'YYYY-MM-DD'), 2700000);
INSERT INTO ISTORIC_ECHIPA_PILOT_F1 VALUES (contract_seq.NEXTVAL, 9, 17, TO_DATE('2025-02-26', 'YYYY-MM-DD'), TO_DATE('2028-02-26', 'YYYY-MM-DD'), 11800000);
INSERT INTO ISTORIC_ECHIPA_PILOT_F1 VALUES (contract_seq.NEXTVAL, 9, 18, TO_DATE('2025-03-01', 'YYYY-MM-DD'), TO_DATE('2029-03-01', 'YYYY-MM-DD'), 3400000);
INSERT INTO ISTORIC_ECHIPA_PILOT_F1 VALUES (contract_seq.NEXTVAL, 10, 19, TO_DATE('2025-03-05', 'YYYY-MM-DD'), TO_DATE('2028-03-05', 'YYYY-MM-DD'), 5600000);
INSERT INTO ISTORIC_ECHIPA_PILOT_F1 VALUES (contract_seq.NEXTVAL, 10, 20, TO_DATE('2025-03-08', 'YYYY-MM-DD'), TO_DATE('2029-03-08', 'YYYY-MM-DD'), 9100000);


select * from ISTORIC_ECHIPA_PILOT_F1;


INSERT INTO VEHICUL_F1 (id_echipa, id_model, greutate, pneuri, pret, data_inspectie)  VALUES (1, 1, 794, 'Pirelli', 15500000.00, TO_DATE('2025-01-12', 'YYYY-MM-DD'));
INSERT INTO VEHICUL_F1 (id_echipa, id_model, greutate, pneuri, pret, data_inspectie)  VALUES (2, 2, 792, 'Michelin', 15200000.00, TO_DATE('2025-04-27', 'YYYY-MM-DD'));
INSERT INTO VEHICUL_F1 (id_echipa, id_model, greutate, pneuri, pret, data_inspectie)  VALUES (3, 3, 780, 'Bridgestone', 15400000.00, TO_DATE('2025-02-03', 'YYYY-MM-DD'));
INSERT INTO VEHICUL_F1 (id_echipa, id_model, greutate, pneuri, pret, data_inspectie)  VALUES (4, 4, 783, 'Goodyear', 14800000.00, TO_DATE('2025-06-18', 'YYYY-MM-DD'));
INSERT INTO VEHICUL_F1 (id_echipa, id_model, greutate, pneuri, pret, data_inspectie)  VALUES (5, 5, 790, 'Pirelli', 14200000.00, TO_DATE('2025-07-29', 'YYYY-MM-DD'));
INSERT INTO VEHICUL_F1 (id_echipa, id_model, greutate, pneuri, pret, data_inspectie)  VALUES (6, 6, 799, 'Michelin', 13500000.00, TO_DATE('2025-03-11', 'YYYY-MM-DD'));
INSERT INTO VEHICUL_F1 (id_echipa, id_model, greutate, pneuri, pret, data_inspectie)  VALUES (7, 7, 791, 'Continental', 12500000.00, TO_DATE('2025-09-22', 'YYYY-MM-DD'));
INSERT INTO VEHICUL_F1 (id_echipa, id_model, greutate, pneuri, pret, data_inspectie)  VALUES (8, 8, 787, 'Michelin', 12800000.00, TO_DATE('2025-02-14', 'YYYY-MM-DD'));
INSERT INTO VEHICUL_F1 (id_echipa, id_model, greutate, pneuri, pret, data_inspectie)  VALUES (9, 9, 788, 'Goodyear', 11900000.00, TO_DATE('2025-08-03', 'YYYY-MM-DD'));
INSERT INTO VEHICUL_F1 (id_echipa, id_model, greutate, pneuri, pret, data_inspectie)  VALUES (10, 10, 795, 'Continental', 11000000.00, TO_DATE('2025-11-19', 'YYYY-MM-DD'));


select * from vehicul_f1;


INSERT INTO CURSA_F1 VALUES (1, 1, 'Grand Prix', TO_DATE('2025-01-05', 'YYYY-MM-DD'), 90, '1:31.447', 'Clear', 'Finished');
INSERT INTO CURSA_F1 VALUES (2, 2, 'Qualifying', TO_DATE('2025-02-17', 'YYYY-MM-DD'), 60, '1:27.472', 'Clear', 'Finished');
INSERT INTO CURSA_F1 VALUES (3, 3, 'Practice Session', TO_DATE('2025-03-11', 'YYYY-MM-DD'), 60, '1:19.813', 'Sunny', 'Finished');
INSERT INTO CURSA_F1 VALUES (4, 4, 'Grand Prix', TO_DATE('2025-04-28', 'YYYY-MM-DD'), 45, '1:33.706', 'Rain', 'Suspended');
INSERT INTO CURSA_F1 VALUES (5, 5, 'Sprint Race', TO_DATE('2025-05-09', 'YYYY-MM-DD'), 35, '1:32.238', 'Cloudy', 'Finished');
INSERT INTO CURSA_F1 VALUES (6, 6, 'Grand Prix', TO_DATE('2025-06-03', 'YYYY-MM-DD'), 94, '1:27.382', 'Sunny', 'Finished');
INSERT INTO CURSA_F1 VALUES (7, 7, 'Practice Session', TO_DATE('2025-07-14', 'YYYY-MM-DD'), 0, 'N/A', 'Storm', 'Cancelled');
INSERT INTO CURSA_F1 VALUES (8, 8, 'Grand Prix', TO_DATE('2025-08-19', 'YYYY-MM-DD'), 120, '1:10.232', 'Clear', 'Finished');
INSERT INTO CURSA_F1 VALUES (9, 9, 'Grand Prix', TO_DATE('2025-09-07', 'YYYY-MM-DD'), 95, '1:11.876', 'Rain', 'Planned');
INSERT INTO CURSA_F1 VALUES (10, 10, 'Sprint Race', TO_DATE('2025-10-21', 'YYYY-MM-DD'), 30, '1:13.200', 'Sunny', 'Planned');


select * from cursa_f1;


INSERT INTO BILET_F1 (id_cursa, id_tip_bilet, loc_tribuna, loc_rand, loc_numar, data_achizitie, stare) VALUES (1, 1, 'A1', 1, 1, TO_DATE('2024-02-14', 'YYYY-MM-DD'), 'SOLD');
INSERT INTO BILET_F1 (id_cursa, id_tip_bilet, loc_tribuna, loc_rand, loc_numar, data_achizitie, stare) VALUES (2, 2, 'T3', 2, 2, TO_DATE('2024-03-05', 'YYYY-MM-DD'), 'SOLD');
INSERT INTO BILET_F1 (id_cursa, id_tip_bilet, loc_tribuna, loc_rand, loc_numar, data_achizitie, stare) VALUES (3, 3, 'B3', 3, 3, TO_DATE('2024-01-22', 'YYYY-MM-DD'), 'SOLD');
INSERT INTO BILET_F1 (id_cursa, id_tip_bilet, loc_tribuna, loc_rand, loc_numar, data_achizitie, stare) VALUES (4, 4, 'C2', 4, 4, TO_DATE('2024-04-11', 'YYYY-MM-DD'), 'SOLD');
INSERT INTO BILET_F1 (id_cursa, id_tip_bilet, loc_tribuna, loc_rand, loc_numar, data_achizitie, stare) VALUES (5, 5, 'D5', 5, 5, TO_DATE('2024-02-27', 'YYYY-MM-DD'), 'SOLD');
INSERT INTO BILET_F1 (id_cursa, id_tip_bilet, loc_tribuna, loc_rand, loc_numar, data_achizitie, stare) VALUES (6, 6, 'E1', 6, 6, TO_DATE('2024-03-29', 'YYYY-MM-DD'), 'SOLD');
INSERT INTO BILET_F1 (id_cursa, id_tip_bilet, loc_tribuna, loc_rand, loc_numar, data_achizitie, stare) VALUES (7, 2, 'F4', 7, 7, TO_DATE('2024-05-03', 'YYYY-MM-DD'), 'SOLD');
INSERT INTO BILET_F1 (id_cursa, id_tip_bilet, loc_tribuna, loc_rand, loc_numar, data_achizitie, stare) VALUES (8, 3, 'G2', 8, 8, TO_DATE('2024-06-18', 'YYYY-MM-DD'), 'SOLD');
INSERT INTO BILET_F1 (id_cursa, id_tip_bilet, loc_tribuna, loc_rand, loc_numar, data_achizitie, stare) VALUES (9, 4, 'H3', 9, 9, TO_DATE('2024-07-09', 'YYYY-MM-DD'), 'SOLD');
INSERT INTO BILET_F1 (id_cursa, id_tip_bilet, loc_tribuna, loc_rand, loc_numar, data_achizitie, stare) VALUES (10, 5, 'J1', 10, 10, TO_DATE('2024-08-25', 'YYYY-MM-DD'), 'VALID');

select * from bilet_f1;


INSERT INTO ECHIPA_SPONSOR_F1 VALUES (1, 1, 100000000.00, 'YES');
INSERT INTO ECHIPA_SPONSOR_F1  VALUES (2, 2, 75000000.00, 'YES');
INSERT INTO ECHIPA_SPONSOR_F1  VALUES (3, 3, 40000000.00, 'YES');
INSERT INTO ECHIPA_SPONSOR_F1  VALUES (4, 4, 30000000.00, 'YES');
INSERT INTO ECHIPA_SPONSOR_F1  VALUES (5, 5, 60000000.00, 'YES');
INSERT INTO ECHIPA_SPONSOR_F1  VALUES (6, 6, 35000000.00, 'YES');
INSERT INTO ECHIPA_SPONSOR_F1  VALUES (7, 8, 20000000.00, 'YES');
INSERT INTO ECHIPA_SPONSOR_F1  VALUES (8, 8, 15000000.00, 'YES');
INSERT INTO ECHIPA_SPONSOR_F1  VALUES (9, 9, 45000000.00, 'YES');
INSERT INTO ECHIPA_SPONSOR_F1  VALUES (10, 10, 25000000.00, 'YES');

select * from echipa_sponsor_f1;


INSERT INTO PILOT_CURSA_F1  VALUES (1, 1, 1, 1);
INSERT INTO PILOT_CURSA_F1  VALUES (2, 1, 5, 2);
INSERT INTO PILOT_CURSA_F1  VALUES (3, 1, 2, 4);
INSERT INTO PILOT_CURSA_F1  VALUES (4, 1, 4, 3);
INSERT INTO PILOT_CURSA_F1  VALUES (5, 1, 9, 7);
INSERT INTO PILOT_CURSA_F1  VALUES (6, 1, 3, 5);
INSERT INTO PILOT_CURSA_F1  VALUES (7, 1, 7, 6);
INSERT INTO PILOT_CURSA_F1  VALUES (8, 1, 8, 8);
INSERT INTO PILOT_CURSA_F1  VALUES (9, 1, 6, 9);
INSERT INTO PILOT_CURSA_F1  VALUES (10, 1, 12, 10);


select * from pilot_cursa_f1;



-------------------------------------------------------------------------------------------


-- 6

-- Conducerea campionatului de Formula 1 doreste o situatie financiara si administrativa a celor mai noi echipe intrate in competitie. 
-- Sa se realizeze o procedura care identifica cele mai noi 5 echipe infiintate si genereaza un raport cu numele, bugetul si numarul sponsorilor activi (status 'YES') ai acestora. 
-- Pentru o procesare eficienta, datele sunt gestionate folosind trei tipuri de colectii: VARRAY, tabele imbricate si tablouri asociative.


CREATE OR REPLACE PROCEDURE p_analiza_echipe IS
    TYPE varray_echipe IS VARRAY(5) OF VARCHAR(100);
    lista_echipe varray_echipe := varray_echipe();

    TYPE tbl_bugete IS TABLE OF NUMBER;
    bugete tbl_bugete := tbl_bugete();

    TYPE tbl_nr_sponsori IS TABLE OF NUMBER INDEX BY VARCHAR(100);
    nr_sponsori tbl_nr_sponsori;

BEGIN
    SELECT nume BULK COLLECT INTO lista_echipe
    FROM ECHIPA_F1
    ORDER BY an_infiintare DESC
    FETCH FIRST 5 ROWS ONLY;

    bugete.EXTEND(lista_echipe.COUNT);
    FOR i IN 1 .. lista_echipe.COUNT LOOP
        SELECT buget INTO bugete(i)
        FROM ECHIPA_F1
        WHERE nume = lista_echipe(i);
        
    END LOOP;

    FOR i IN 1 .. lista_echipe.COUNT LOOP
        SELECT COUNT(*) INTO nr_sponsori(lista_echipe(i))
        FROM ECHIPA_SPONSOR_F1 ES
        JOIN ECHIPA_F1 E ON E.id_echipa = ES.id_echipa
        WHERE E.nume = lista_echipe(i) AND ES.status_activ = 'YES';
    END LOOP;

    DBMS_OUTPUT.PUT_LINE('--- Primele 5 echipe cele mai noi infiintate ---');
    DBMS_OUTPUT.PUT_LINE('');
    FOR i IN 1 .. lista_echipe.COUNT LOOP
        DBMS_OUTPUT.PUT_LINE('Echipa: ' || lista_echipe(i));
        DBMS_OUTPUT.PUT_LINE(' - Buget: ' || bugete(i));
        DBMS_OUTPUT.PUT_LINE(' - Numar sponsori activi: ' || nr_sponsori(lista_echipe(i)));
        DBMS_OUTPUT.PUT_LINE('---------------------------');
    END LOOP;

END;

BEGIN
    p_analiza_echipe;
END;


-- 7

-- Departamentul administrativ al FIA doreste monitorizarea situatiei contractuale a pilotilor din campionatul curent. 
-- Pentru o organizare eficienta, este necesara vizualizarea pilotilor grupati in functie de echipa la care sunt legitimati.
-- Sa se realizeze un subprogram stocat independent (procedura) care sa genereze un raport al contractelor active. 


CREATE OR REPLACE PROCEDURE p_raport_piloti_activi IS
    CURSOR cursor_piloti_activi (id_echipa_importata NUMBER) 
    IS
        SELECT P.nume, P.prenume, I.salariu, I.data_final
        FROM ISTORIC_ECHIPA_PILOT_F1 I
        JOIN PILOT_F1 P ON I.id_pilot = P.id_pilot
        WHERE I.id_echipa = id_echipa_importata AND I.data_final >= SYSDATE;

    nume_pilot      PILOT_F1.nume%TYPE;
    prenume_pilot   PILOT_F1.prenume%TYPE;
    salariu_angajat ISTORIC_ECHIPA_PILOT_F1.salariu%TYPE;
    data_expirare   ISTORIC_ECHIPA_PILOT_F1.data_final%TYPE;

BEGIN
    DBMS_OUTPUT.PUT_LINE('=== PILOTI CU CONTRACTE ACTIVE ===');
    DBMS_OUTPUT.PUT_LINE('');

    FOR echipa_curenta IN (SELECT id_echipa, nume FROM ECHIPA_F1 ORDER BY nume) LOOP
        DBMS_OUTPUT.PUT_LINE('Echipa: ' || echipa_curenta.nume);

        OPEN cursor_piloti_activi(echipa_curenta.id_echipa);
        
        LOOP
            FETCH cursor_piloti_activi INTO nume_pilot, prenume_pilot, salariu_angajat, data_expirare;
            EXIT WHEN cursor_piloti_activi%NOTFOUND;
            
            DBMS_OUTPUT.PUT_LINE('-> ' || nume_pilot || ' ' || prenume_pilot || ' | Salariu ' || salariu_angajat || ' EURO | ' || '(Expira la: ' || TO_CHAR(data_expirare, 'DD.MM.YYYY') || ')');
        END LOOP;

        IF cursor_piloti_activi%ROWCOUNT=0 THEN
            DBMS_OUTPUT.PUT_LINE('-> (Niciun pilot activ gasit)');
        END IF;

        CLOSE cursor_piloti_activi;
        DBMS_OUTPUT.PUT_LINE('----------------------------------');
        
    END LOOP;
END;

BEGIN
    p_raport_piloti_activi;
END;


-- 8

-- Mecanicii fiecarei echipe au nevoie de o metoda rapida pentru a identifica modelul de masina care detine recordul de viteza din garajul lor. 
-- Se va realiza o functie care primeste codul echipei si returneaza denumirea celui mai rapid model, interogand simultan tabelele ECHIPA_F1, VEHICUL_F1 si MODEL_VEHICUL_F1. 
-- Inspectorii tehnici vor folosi acest subprogram pentru a valida datele, functia gestionand exceptiile pentru coduri de echipa inexistente, lipsa masinilor din inventar 
-- sau existenta mai multor modele cu aceeasi viteza maxima.


CREATE OR REPLACE FUNCTION f_model_cel_mai_rapid_echipa (
    id_echipa_cautata IN NUMBER
) 
RETURN VARCHAR
IS
    nume_model MODEL_VEHICUL_F1.nume%TYPE;
    exista_echipa NUMBER;

    ECHIPA_INEXISTENTA EXCEPTION;
BEGIN
    SELECT COUNT(*) INTO exista_echipa
    FROM ECHIPA_F1
    WHERE id_echipa = id_echipa_cautata;

    IF exista_echipa = 0 THEN
        RAISE ECHIPA_INEXISTENTA;
    END IF;

    SELECT DISTINCT MV.nume INTO nume_model
    FROM ECHIPA_F1 E
    JOIN VEHICUL_F1 V ON E.id_echipa = V.id_echipa
    JOIN MODEL_VEHICUL_F1 MV ON V.id_model = MV.id_model
    WHERE E.id_echipa = id_echipa_cautata AND MV.viteza_maxima = (
                SELECT MAX(MV2.viteza_maxima)
                FROM VEHICUL_F1 V2
                JOIN MODEL_VEHICUL_F1 MV2 ON V2.id_model = MV2.id_model
                WHERE V2.id_echipa = id_echipa_cautata
                );

    RETURN nume_model;

    EXCEPTION
        WHEN ECHIPA_INEXISTENTA THEN
            DBMS_OUTPUT.PUT_LINE('Eroare: ID-ul ' || id_echipa_cautata || ' nu corespunde niciunei echipe.');
            RETURN NULL;
    
        WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('Eroare: Echipa exista, dar nu are niciun vehicul sau model asociat.');
            RETURN NULL;
    
        WHEN TOO_MANY_ROWS THEN
            DBMS_OUTPUT.PUT_LINE('Eroare: Exista mai multe modele diferite care ating aceeasi viteza maxima.');
            RETURN NULL;
    
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('Eroare neprevazuta: ' || SQLERRM);
            RETURN NULL;
END;


-- CAZUL 1: Succes (ID valid care are vehicule)
BEGIN
    DBMS_OUTPUT.PUT_LINE('Model cel mai rapid: ' || f_model_cel_mai_rapid_echipa(1));
END; 

-- CAZUL 2: Echipa nu exista (Declanseaza ECHIPA_INEXISTENTA)
BEGIN
    DBMS_OUTPUT.PUT_LINE('Rezultat ID inexistent: ' || f_model_cel_mai_rapid_echipa(9999));
END;

-- CAZUL 3: Echipa exista, dar nu are vehicule (Declansează NO_DATA_FOUND)
INSERT INTO ECHIPA_F1 (id_echipa, nume, an_infiintare, buget) VALUES (99, 'Echipa Test Fara Masini', 2025, 0);

BEGIN
    DBMS_OUTPUT.PUT_LINE('Rezultat: ' || f_model_cel_mai_rapid_echipa(99));
END;

DELETE FROM ECHIPA_F1
WHERE id_echipa = 99;

-- CAZUL 4: Mai multe modele au aceeasi viteza maxima (Declanseaza TOO_MANY_ROWS)

INSERT INTO MODEL_VEHICUL_F1 (id_model, nume, viteza_maxima) VALUES (888, 'Model Duplicat Test', 370);
INSERT INTO VEHICUL_F1 (id_vehicul, id_echipa, id_model) VALUES (888, 2, 888);

UPDATE MODEL_VEHICUL_F1 
SET viteza_maxima = 370 
WHERE id_model = (SELECT id_model FROM VEHICUL_F1 WHERE id_echipa = 2 FETCH FIRST 1 ROW ONLY);

BEGIN
    DBMS_OUTPUT.PUT_LINE('Rezultat viteze identice: ' || f_model_cel_mai_rapid_echipa(2));
END;

DELETE FROM MODEL_VEHICUL_F1
WHERE id_model = 888;

DELETE FROM VEHICUL_F1
WHERE id_vehicul = 888;


-- 9 


CREATE OR REPLACE PROCEDURE p_audit_contract_pilot (
    id_pilot_intrare IN NUMBER,
    an_sezon         IN NUMBER
) IS
    nume_complet            VARCHAR2(200);
    cea_mai_buna_pozitie    NUMBER;
    numar_podiumuri         NUMBER := 0;
    salariu_negociat        NUMBER := 0;

    PERFORMANTA_SLABA       EXCEPTION; 
    SALARIU_NEJUSTIFICAT    EXCEPTION; 
BEGIN
    SELECT nume || ' ' || prenume INTO nume_complet 
    FROM PILOT_F1 
    WHERE id_pilot = id_pilot_intrare;

    SELECT MIN(PC.pozitie_finala), COUNT(CASE WHEN PC.pozitie_finala <= 3 THEN 1 END), MAX(H.salariu) INTO cea_mai_buna_pozitie, numar_podiumuri, salariu_negociat
    FROM PILOT_F1 P
    JOIN ISTORIC_ECHIPA_PILOT_F1 H ON P.id_pilot = H.id_pilot
    JOIN ECHIPA_F1 E               ON H.id_echipa = E.id_echipa
    JOIN PILOT_CURSA_F1 PC         ON P.id_pilot = PC.id_pilot
    JOIN CURSA_F1 C                ON PC.id_cursa = C.id_cursa
    WHERE P.id_pilot = id_pilot_intrare AND EXTRACT(YEAR FROM C.data_cursa) = an_sezon AND TRUNC(C.data_cursa) BETWEEN TRUNC(H.data_inceput) AND TRUNC(H.data_final);

    IF cea_mai_buna_pozitie IS NULL THEN
        DBMS_OUTPUT.PUT_LINE('INFO: Pilotul ' || nume_complet || ' nu a participat la curse in anul ' || an_sezon);
        RETURN;
    END IF;

    IF cea_mai_buna_pozitie > 10 THEN
        RAISE PERFORMANTA_SLABA;
    END IF;

    IF salariu_negociat > 5000000 AND numar_podiumuri = 0 THEN
        RAISE SALARIU_NEJUSTIFICAT;
    END IF;

    DBMS_OUTPUT.PUT_LINE('====================================================');
    DBMS_OUTPUT.PUT_LINE('AUDIT CONTRACTUAL REUSIT: ' || nume_complet);
    DBMS_OUTPUT.PUT_LINE('CEA MAI BUNA CLASARE: ' || cea_mai_buna_pozitie);
    DBMS_OUTPUT.PUT_LINE('NUMAR PODIUMURI: ' || numar_podiumuri);
    DBMS_OUTPUT.PUT_LINE('STATUS: OBIECTIVE INDEPLINITE');
    DBMS_OUTPUT.PUT_LINE('====================================================');

EXCEPTION
    WHEN PERFORMANTA_SLABA THEN
        DBMS_OUTPUT.PUT_LINE('ALERTA: Pilotul ' || nume_complet || ' nu a atins TOP 10 (Cea mai buna: ' || cea_mai_buna_pozitie || ').');
    
    WHEN SALARIU_NEJUSTIFICAT THEN
        DBMS_OUTPUT.PUT_LINE('ALERTA: Salariul de ' || salariu_negociat || ' EUR este nejustificat (0 Podiumuri).');

    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('EROARE: ID-ul pilotului nu a fost gasit.');
        
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('EROARE NEASTEPTATA: ' || SQLERRM);
END;


--PERFORMANTA_SLABA
INSERT INTO PILOT_F1 (id_pilot, nume, prenume, data_nastere, nationalitate) VALUES (99, 'Latifi', 'Nicholas', TO_DATE('1995-06-29', 'YYYY-MM-DD'), 'CAN');
INSERT INTO ISTORIC_ECHIPA_PILOT_F1 (id_contract, id_echipa, id_pilot, data_inceput, data_final, salariu) VALUES (999, 10, 99, TO_DATE('2026-01-01', 'YYYY-MM-DD'), TO_DATE('2026-12-31', 'YYYY-MM-DD'), 1000000);
INSERT INTO CURSA_F1 (id_cursa, id_circuit, tip_cursa, data_cursa, status) VALUES (99, 1, 'Grand Prix', TO_DATE('2026-03-15', 'YYYY-MM-DD'), 'Finished');
INSERT INTO PILOT_CURSA_F1 (id_pilot, id_cursa, pozitie_start, pozitie_finala) VALUES (99, 99, 20, 15);

BEGIN
    p_audit_contract_pilot(99, 2026);
END;

-- SALARIU_NEJUSTIFICAT
INSERT INTO PILOT_F1 (id_pilot, nume, prenume, data_nastere, nationalitate) VALUES (88, 'Stroll', 'Lance', TO_DATE('1998-10-29', 'YYYY-MM-DD'), 'CAN');
INSERT INTO ISTORIC_ECHIPA_PILOT_F1 (id_contract, id_echipa, id_pilot, data_inceput, data_final, salariu) VALUES (888, 5, 88, TO_DATE('2026-01-01', 'YYYY-MM-DD'), TO_DATE('2026-12-31', 'YYYY-MM-DD'), 8000000);
INSERT INTO CURSA_F1 (id_cursa, id_circuit, tip_cursa, data_cursa, status) VALUES (88, 2, 'Grand Prix', TO_DATE('2026-04-20', 'YYYY-MM-DD'), 'Finished');
INSERT INTO PILOT_CURSA_F1 (id_pilot, id_cursa, pozitie_start, pozitie_finala) VALUES (88, 88, 5, 5); 

BEGIN
    p_audit_contract_pilot(88, 2026);
END;

-- NO_DATA_FOUND
BEGIN
    p_audit_contract_pilot(7777, 2026);
END;

-- INFO
INSERT INTO PILOT_F1 (id_pilot, nume, prenume, data_nastere, nationalitate) VALUES (55, 'Schumacher', 'Mick', TO_DATE('1999-03-22', 'YYYY-MM-DD'), 'GER');
INSERT INTO ISTORIC_ECHIPA_PILOT_F1 (id_contract, id_echipa, id_pilot, data_inceput, data_final, salariu) VALUES (555, 3, 55, TO_DATE('2026-01-01', 'YYYY-MM-DD'), TO_DATE('2026-12-31', 'YYYY-MM-DD'), 2000000);

BEGIN
    p_audit_contract_pilot(55, 2026);
END;


-- 10


CREATE OR REPLACE TRIGGER trg_restrictie_modificari_masini
BEFORE INSERT OR UPDATE OR DELETE ON VEHICUL_F1
DECLARE
    stare_cursa   VARCHAR(20); 
    nume_circuit  VARCHAR(100);
BEGIN
    stare_cursa := 'Nicio Cursa';
    nume_circuit := 'Nespecificat';

    BEGIN
        SELECT C.status, CIR.nume  INTO stare_cursa, nume_circuit
        FROM CURSA_F1 C
        JOIN CIRCUIT_F1 CIR ON C.id_circuit = CIR.id_circuit
        WHERE TRUNC(C.data_cursa) = TRUNC(SYSDATE)
        AND ROWNUM = 1;
        
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                NULL;
    END;

    IF stare_cursa IN ('In Progress', 'Suspended') THEN
        RAISE_APPLICATION_ERROR(-20001, 'BLOCAJ: Cursa de pe circuitul ' || nume_circuit || ' este ' || stare_cursa || '. Modificarile sunt interzise!');
    ELSIF stare_cursa = 'Planned' THEN
        IF DELETING THEN
            RAISE_APPLICATION_ERROR(-20002, 'RESTRICTIE: Nu puteti sterge vehiculele in ziua cursei ' || nume_circuit);
        END IF;
        DBMS_OUTPUT.PUT_LINE('Verificare: Actualizarile sunt permise pentru pregatirea cursei ' || nume_circuit);
    
    ELSE
        DBMS_OUTPUT.PUT_LINE('Sistem deschis: Nu exista restrictii active pentru vehicule astazi.');
    END IF;
END;


-- REZULTAT: Eroare ORA-20001: "BLOCAJ"
INSERT INTO CURSA_F1 (id_cursa, id_circuit, tip_cursa, data_cursa, status) VALUES (99, 1, 'Grand Prix', SYSDATE, 'In Progress');

UPDATE VEHICUL_F1 
SET greutate = 850 
WHERE id_vehicul = 1;


-- REZULTAT: Eroare ORA-20002: "RESTRICTIE"
UPDATE CURSA_F1 
SET status = 'Planned' 
WHERE id_cursa = 99;

DELETE FROM VEHICUL_F1 
WHERE id_vehicul = 1;

-- REZULTAT : SUCCES
UPDATE CURSA_F1 
SET status = 'Finished' 
WHERE id_cursa = 99;

UPDATE VEHICUL_F1 
SET pneuri = 'Pirelli' 
WHERE id_vehicul = 1;

DELETE FROM CURSA_F1
WHERE id_cursa = 99;


-- 11


CREATE OR REPLACE PACKAGE pachet_limitare_piloti IS
    TYPE colectie_echipe IS TABLE OF NUMBER INDEX BY PLS_INTEGER;
    inventar_echipe colectie_echipe;
END;

CREATE OR REPLACE TRIGGER trg_init_inventar
BEFORE INSERT OR UPDATE ON ISTORIC_ECHIPA_PILOT_F1
BEGIN
    pachet_limitare_piloti.inventar_echipe.DELETE;

    FOR rand IN (
        SELECT id_echipa, COUNT(*) as total 
        FROM ISTORIC_ECHIPA_PILOT_F1 
        WHERE TRUNC(SYSDATE) BETWEEN TRUNC(data_inceput) AND TRUNC(data_final)
        GROUP BY id_echipa
    ) LOOP
        pachet_limitare_piloti.inventar_echipe(rand.id_echipa) := rand.total;
    END LOOP;
END;


CREATE OR REPLACE TRIGGER trg_ajustare_linie
BEFORE INSERT OR UPDATE OF id_echipa, data_inceput, data_final ON ISTORIC_ECHIPA_PILOT_F1
FOR EACH ROW
DECLARE
    echipa_noua   NUMBER := :NEW.id_echipa;
    echipa_veche  NUMBER := :OLD.id_echipa;
BEGIN
    IF UPDATING THEN
        IF TRUNC(SYSDATE) BETWEEN TRUNC(:OLD.data_inceput) AND TRUNC(:OLD.data_final) THEN
            IF pachet_limitare_piloti.inventar_echipe.EXISTS(echipa_veche) THEN
                pachet_limitare_piloti.inventar_echipe(echipa_veche) := pachet_limitare_piloti.inventar_echipe(echipa_veche) - 1;
            END IF;
        END IF;
    END IF;

    IF TRUNC(SYSDATE) BETWEEN TRUNC(:NEW.data_inceput) AND TRUNC(:NEW.data_final) THEN
        IF NOT pachet_limitare_piloti.inventar_echipe.EXISTS(echipa_noua) THEN
            pachet_limitare_piloti.inventar_echipe(echipa_noua) := 0;
        END IF;

        pachet_limitare_piloti.inventar_echipe(echipa_noua) := pachet_limitare_piloti.inventar_echipe(echipa_noua) + 1;
    END IF;
END;


CREATE OR REPLACE TRIGGER trg_validare_limita
AFTER INSERT OR UPDATE ON ISTORIC_ECHIPA_PILOT_F1
DECLARE
    cheie_echipa  NUMBER;
BEGIN
    cheie_echipa := pachet_limitare_piloti.inventar_echipe.FIRST;

    WHILE cheie_echipa IS NOT NULL LOOP
        IF pachet_limitare_piloti.inventar_echipe(cheie_echipa) > 3 THEN
            RAISE_APPLICATION_ERROR(-20005, 'LIMITA DEPASITA: Echipa ' || cheie_echipa || ' are ' || pachet_limitare_piloti.inventar_echipe(cheie_echipa) || ' piloti activi!');
        END IF;
        
        cheie_echipa := pachet_limitare_piloti.inventar_echipe.NEXT(cheie_echipa);
    END LOOP;
END;


INSERT INTO PILOT_F1 VALUES (100, 'SGBD', 'EXAMEN', TO_DATE('1900-04-23', 'YYYY-MM-DD'), 'ROU', 6000, 10);
INSERT INTO PILOT_F1 VALUES (101, 'SESIUNE', 'NOTA_10', TO_DATE('1900-04-23', 'YYYY-MM-DD'), 'ROU', 1000, 3);
INSERT INTO ISTORIC_ECHIPA_PILOT_F1 (id_contract, id_echipa, id_pilot, data_inceput, data_final, salariu) VALUES (830, 1, 100, SYSDATE - 2, SYSDATE + 20, 700000);
INSERT INTO ISTORIC_ECHIPA_PILOT_F1 (id_contract, id_echipa, id_pilot, data_inceput, data_final, salariu) VALUES (831, 1, 101, SYSDATE - 2, SYSDATE + 20, 700000);


-- 12


DROP TABLE AUDIT_LDD_F1;

CREATE TABLE AUDIT_LDD_F1 (
    id_audit       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilizator     VARCHAR(50),
    eveniment      VARCHAR(50),
    tip_obiect     VARCHAR(50),
    nume_obiect    VARCHAR(100),
    data_ora       DATE,
    status         VARCHAR(20)
);

CREATE OR REPLACE PROCEDURE tracker_eveniment_ldd (
    nume_utilizator VARCHAR, 
    tip_ev          VARCHAR, 
    tip_obj         VARCHAR, 
    nume_obj        VARCHAR, 
    stare           VARCHAR
) 
IS
    PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
    INSERT INTO AUDIT_LDD_F1 (utilizator, eveniment, tip_obiect, nume_obiect, data_ora, status) VALUES (nume_utilizator, tip_ev, tip_obj, nume_obj, SYSDATE, stare);
    COMMIT;
END;

CREATE OR REPLACE TRIGGER trg_ldd_audit_f1
BEFORE CREATE OR ALTER OR DROP ON SCHEMA
DECLARE
    utilizator_curent     VARCHAR(50)  := SYS.LOGIN_USER;
    eveniment_sistem      VARCHAR(50)  := SYSEVENT;
    numele_obiectului     VARCHAR(100) := SYS.DICTIONARY_OBJ_NAME;
    tipul_obiectului      VARCHAR(50)  := SYS.DICTIONARY_OBJ_TYPE;
BEGIN
    IF (TO_CHAR(SYSDATE, 'D') = 1) OR (TO_NUMBER(TO_CHAR(SYSDATE, 'HH24')) NOT BETWEEN 8 AND 20) 
    THEN 
        tracker_eveniment_ldd(utilizator_curent, eveniment_sistem, tipul_obiectului, numele_obiectului, 'BLOCAT (ORA/ZI)'); 
        RAISE_APPLICATION_ERROR(-20006, 'MENTENANTA: Utilizatorule ' || utilizator_curent || ', modificarile sunt permise doar Luni-Sambata (08:00 - 20:00)!'); 
    END IF;

    IF eveniment_sistem = 'CREATE' AND tipul_obiectului = 'TABLE' THEN
        IF UPPER(numele_obiectului) NOT LIKE '%_F1' THEN
            tracker_eveniment_ldd(utilizator_curent, eveniment_sistem, tipul_obiectului, numele_obiectului, 'BLOCAT (NUME)');
            RAISE_APPLICATION_ERROR(-20007, 'PROTOCOL: Numele tabelului creat de ' || utilizator_curent || ' trebuie sa se termine in _F1!');
        END IF;
    END IF;

    IF eveniment_sistem = 'DROP' AND tipul_obiectului = 'TABLE' THEN
        IF UPPER(numele_obiectului) LIKE '%_F1' THEN
            tracker_eveniment_ldd(utilizator_curent, eveniment_sistem, tipul_obiectului, numele_obiectului, 'BLOCAT (PROTECTIE)');
            RAISE_APPLICATION_ERROR(-20008, 'SECURITATE: Utilizatorul ' || utilizator_curent || ' nu are permisiunea sa stearga ' || numele_obiectului || '!');
        END IF;
    END IF;

    tracker_eveniment_ldd(utilizator_curent, eveniment_sistem, tipul_obiectului, numele_obiectului, 'REUSIT');
END;


DROP TABLE TEST_F1;
DROP TABLE TEST;

CREATE TABLE TEST_F1 (id NUMBER);

CREATE TABLE TEST (id NUMBER);

SELECT * FROM AUDIT_LDD_F1 
WHERE nume_obiect = 'TEST_F1';

SELECT * FROM AUDIT_LDD_F1;

ALTER TRIGGER trg_ldd_audit_f1 DISABLE;
ALTER TRIGGER trg_ldd_audit_f1 ENABLE;

DROP TRIGGER trg_ldd_audit_f1;


-- 13


CREATE OR REPLACE PACKAGE PKG_ANALIZA_PILOT IS
    TYPE info_cursa_rec IS RECORD (
        id_cursa       CURSA_F1.id_cursa%TYPE,
        tip_cursa      CURSA_F1.tip_cursa%TYPE,
        data_cursa     CURSA_F1.data_cursa%TYPE,
        pozitie_finala PILOT_CURSA_F1.pozitie_finala%TYPE
    );

    TYPE lista_curse_tab IS TABLE OF info_cursa_rec INDEX BY PLS_INTEGER;

    FUNCTION nr_curse_pilot (identificator_pilot IN PILOT_F1.id_pilot%TYPE, an_sezon IN NUMBER) 
    RETURN NUMBER;

    FUNCTION pozitie_medie_pilot (identificator_pilot IN PILOT_F1.id_pilot%TYPE, an_sezon IN NUMBER) 
    RETURN NUMBER;

    PROCEDURE incarca_curse_pilot (identificator_pilot IN PILOT_F1.id_pilot%TYPE, an_sezon IN NUMBER, colectie_curse OUT lista_curse_tab);

    PROCEDURE raport_pilot_sezon (identificator_pilot IN PILOT_F1.id_pilot%TYPE, an_sezon IN NUMBER);

END PKG_ANALIZA_PILOT;

CREATE OR REPLACE PACKAGE BODY PKG_ANALIZA_PILOT IS

    FUNCTION nr_curse_pilot (identificator_pilot IN PILOT_F1.id_pilot%TYPE, an_sezon IN NUMBER) 
    RETURN NUMBER 
    IS
        numar_total NUMBER;
    BEGIN
        SELECT COUNT(*) INTO numar_total 
        FROM PILOT_CURSA_F1 PC
        JOIN CURSA_F1 C ON PC.id_cursa = C.id_cursa
        WHERE PC.id_pilot = identificator_pilot AND EXTRACT(YEAR FROM C.data_cursa) = an_sezon;

        RETURN numar_total;
    END nr_curse_pilot;

    FUNCTION pozitie_medie_pilot (identificator_pilot IN PILOT_F1.id_pilot%TYPE, an_sezon IN NUMBER) 
    RETURN NUMBER 
    IS
        valoare_medie NUMBER;
    BEGIN
        SELECT AVG(pc.pozitie_finala) INTO valoare_medie
        FROM PILOT_CURSA_F1 pc
        JOIN CURSA_F1 c ON PC.id_cursa = C.id_cursa
        WHERE PC.id_pilot = identificator_pilot AND EXTRACT(YEAR FROM C.data_cursa) = an_sezon;

        RETURN valoare_medie;
    END pozitie_medie_pilot;

    PROCEDURE incarca_curse_pilot (identificator_pilot IN PILOT_F1.id_pilot%TYPE, an_sezon IN NUMBER, colectie_curse OUT lista_curse_tab)
    IS
        contor NUMBER := 0;
    BEGIN
        FOR r_cursa IN (
            SELECT C.id_cursa, C.tip_cursa, C.data_cursa, PC.pozitie_finala 
            FROM PILOT_CURSA_F1 PC
            JOIN CURSA_F1 C ON PC.id_cursa = C.id_cursa
            WHERE PC.id_pilot = identificator_pilot AND EXTRACT(YEAR FROM C.data_cursa) = an_sezon
            ORDER BY C.data_cursa
        )
        LOOP
            contor := contor + 1;
            colectie_curse(contor).id_cursa := r_cursa.id_cursa;
            colectie_curse(contor).tip_cursa := r_cursa.tip_cursa;
            colectie_curse(contor).data_cursa := r_cursa.data_cursa;
            colectie_curse(contor).pozitie_finala := r_cursa.pozitie_finala;
        END LOOP;
    END incarca_curse_pilot;

    PROCEDURE raport_pilot_sezon (identificator_pilot IN PILOT_F1.id_pilot%TYPE, an_sezon IN NUMBER) 
    IS
        tabel_curse   lista_curse_tab;
        numar_curse   NUMBER;
        medie_pozitie NUMBER;
        nume_pilot    VARCHAR2(100);
    BEGIN
        SELECT nume || ' ' || prenume INTO nume_pilot 
        FROM PILOT_F1 
        WHERE id_pilot = identificator_pilot;

        incarca_curse_pilot(identificator_pilot, an_sezon, tabel_curse);
        numar_curse   := nr_curse_pilot(identificator_pilot, an_sezon);
        medie_pozitie := pozitie_medie_pilot(identificator_pilot, an_sezon);

        DBMS_OUTPUT.PUT_LINE('====================================================');
        DBMS_OUTPUT.PUT_LINE('RAPORT SEZON: ' || an_sezon);
        DBMS_OUTPUT.PUT_LINE('PILOT: ' || nume_pilot || ' (ID: ' || identificator_pilot || ')');
        DBMS_OUTPUT.PUT_LINE('----------------------------------------------------');
        DBMS_OUTPUT.PUT_LINE('Total curse participat: ' || numar_curse);
        DBMS_OUTPUT.PUT_LINE('Pozitie medie obtinuta: ' || ROUND(NVL(medie_pozitie, 0), 2));
        DBMS_OUTPUT.PUT_LINE('----------------------------------------------------');

        IF tabel_curse.COUNT > 0 THEN
            FOR i IN tabel_curse.FIRST .. tabel_curse.LAST LOOP
                DBMS_OUTPUT.PUT_LINE('Cursa ID: ' || tabel_curse(i).id_cursa || ' | Tip: ' || tabel_curse(i).tip_cursa || ' | Data: ' || TO_CHAR(tabel_curse(i).data_cursa, 'DD-MM-YYYY') || ' | Pozitie: ' || tabel_curse(i).pozitie_finala);
            END LOOP;
        ELSE
            DBMS_OUTPUT.PUT_LINE('Nu exista participari inregistrate in acest an.');
        END IF;
        DBMS_OUTPUT.PUT_LINE('====================================================');
    END raport_pilot_sezon;

END PKG_ANALIZA_PILOT;


BEGIN
    PKG_ANALIZA_PILOT.raport_pilot_sezon(1, 2025);
END;
