SET SERVEROUTPUT ON;

DROP TABLE PILOT_CURSA_F1;
DROP TABLE ECHIPA_SPONSOR_F1;
DROP TABLE BILET_F1;
DROP TABLE CURSA_F1;
DROP TABLE VEHICUL_F1;
DROP TABLE ISTORIC_ECHIPA_PILOT;
DROP TABLE PILOT_F1;
DROP TABLE ECHIPA_F1;
DROP TABLE TIP_BILET_F1;
DROP TABLE CIRCUIT_F1;
DROP TABLE MODEL_VEHICUL_F1;
DROP TABLE SPONSOR_F1;



DROP SEQUENCE tip_bilet_seq;
DROP SEQUENCE pilot_seq;
DROP SEQUENCE echipa_seq;
DROP SEQUENCE circuit_seq;
DROP SEQUENCE contract_seq;


CREATE SEQUENCE tip_bilet_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE pilot_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE echipa_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE circuit_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE contract_seq START WITH 101 INCREMENT BY 1;


-- 1. SPONSOR_F1 (Standard)
CREATE TABLE SPONSOR_F1 (
    id_sponsor INT PRIMARY KEY,
    nume VARCHAR(100) NOT NULL,
    tip_parteneriat VARCHAR(50),
    domeniu VARCHAR(50)
);

-- 2. MODEL_VEHICUL_F1 (Standard)
CREATE TABLE MODEL_VEHICUL_F1 (
    id_model INT PRIMARY KEY,
    nume VARCHAR(100),
    aerodinamica VARCHAR(50),
    viteza_maxima INT 
);

-- 3. CIRCUIT_F1 (Are secventa circuit_seq creata separat)
CREATE TABLE CIRCUIT_F1 (
    id_circuit INT PRIMARY KEY,
    nume VARCHAR(100) NOT NULL,
    tara VARCHAR(50),
    oras VARCHAR(50),
    lungime DECIMAL(5, 3), 
    viraje INT,
    drs_zone INT
);

-- 4. TIP_BILET_F1 (Are secventa tip_bilet_seq creata separat)
CREATE TABLE TIP_BILET_F1 (
    id_tip_bilet INT PRIMARY KEY,
    categorie VARCHAR(50),
    acces_pitstop CHAR(3) CHECK (acces_pitstop IN ('YES', 'NO'))
);

-- 5. ECHIPA_F1 (Are secventa echipa_seq creata separat)
CREATE TABLE ECHIPA_F1 (
    id_echipa INT PRIMARY KEY,
    nume VARCHAR(100) NOT NULL,
    sediu VARCHAR(100),
    buget DECIMAL(15, 2),
    an_infiintare INT
);

-- 6. PILOT_F1 (Are secventa pilot_seq creata separat)
CREATE TABLE PILOT_F1 (
    id_pilot INT PRIMARY KEY,
    nume VARCHAR(50),
    prenume VARCHAR(50),
    data_nastere DATE,
    nationalitate VARCHAR(50),
    puncte INT DEFAULT 0,
    titluri INT DEFAULT 0
);

-- 7. VEHICUL_F1 (IDENTITY - ASA CUM AI CERUT)
CREATE TABLE VEHICUL_F1 (
    id_vehicul INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Aici e modificarea
    
    id_echipa INT NOT NULL, 
    id_model INT NOT NULL, 
    greutate INT, 
    pneuri VARCHAR(50), 
    pret DECIMAL(15, 2),
    data_inspectie DATE,
    
    FOREIGN KEY (id_echipa) REFERENCES ECHIPA_F1(id_echipa),
    FOREIGN KEY (id_model) REFERENCES MODEL_VEHICUL_F1(id_model)
);

-- 8. CURSA_F1 (Standard)
CREATE TABLE CURSA_F1 (
    id_cursa INT PRIMARY KEY,
    id_circuit INT NOT NULL, 
    tip_cursa VARCHAR(50) CHECK (tip_cursa IN ('Grand Prix', 'Sprint Race', 'Test Session')),
    data_cursa DATE,
    durata INT, 
    record_timp VARCHAR(20),
    vreme VARCHAR(50),
    status VARCHAR(20) CHECK (status IN ('In Progress', 'Cancelled', 'Suspended', 'Finished')),
    
    FOREIGN KEY (id_circuit) REFERENCES CIRCUIT_F1(id_circuit)
);

-- 9. BILET_F1 (IDENTITY - ASA CUM AI CERUT)
CREATE TABLE BILET_F1 (
    id_bilet INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Aici e modificarea
    
    id_cursa INT NOT NULL,
    id_tip_bilet INT NOT NULL,
    loc_tribuna VARCHAR(10),
    loc_rand INT,
    loc_numar INT,
    data_achizitie DATE,
    stare VARCHAR(20) CHECK (stare IN ('SOLD', 'VALID')),
    
    FOREIGN KEY (id_cursa) REFERENCES CURSA_F1(id_cursa),
    FOREIGN KEY (id_tip_bilet) REFERENCES TIP_BILET_F1(id_tip_bilet)
);

-- 10. ECHIPA_SPONSOR_F1 (M:N)
CREATE TABLE ECHIPA_SPONSOR_F1 (
    id_echipa INT,
    id_sponsor INT,
    PRIMARY KEY (id_echipa, id_sponsor),
    contributie_financiara DECIMAL(15, 2),
    status_activ VARCHAR2(3) CHECK (status_activ IN ('YES', 'NO')),
    
    FOREIGN KEY (id_echipa) REFERENCES ECHIPA_F1(id_echipa),
    FOREIGN KEY (id_sponsor) REFERENCES SPONSOR_F1(id_sponsor)
);

-- 11. PILOT_CURSA_F1 (M:N)
CREATE TABLE PILOT_CURSA_F1 (
    id_pilot INT,
    id_cursa INT,
    PRIMARY KEY (id_pilot, id_cursa),
    pozitie_start INT,
    pozitie_finala INT,
    
    FOREIGN KEY (id_pilot) REFERENCES PILOT_F1(id_pilot),
    FOREIGN KEY (id_cursa) REFERENCES CURSA_F1(id_cursa)
);

--12. ISTORIC_ECHIPA_PILOT
CREATE TABLE ISTORIC_ECHIPA_PILOT (
    id_contract INT PRIMARY KEY,
    id_echipa INT NOT NULL,
    id_pilot INT NOT NULL,
    
    data_inceput DATE NOT NULL,
    data_final DATE NOT NULL,
    salariu DECIMAL(15, 2),
    
    FOREIGN KEY (id_echipa) REFERENCES ECHIPA_F1(id_echipa),
    FOREIGN KEY (id_pilot) REFERENCES PILOT_F1(id_pilot)
);



-------------------------------------------------------------------------------------------

-- DONE ✅ 
INSERT INTO SPONSOR_F1 VALUES (1, 'Oracle', 'Title', 'Tech');
INSERT INTO SPONSOR_F1 VALUES (2, 'Petronas', 'Title', 'Energy');
INSERT INTO SPONSOR_F1 VALUES (3, 'Shell', 'Technical', 'Fuel');
INSERT INTO SPONSOR_F1 VALUES (4, 'Aramco', 'Strategic', 'Energy');
INSERT INTO SPONSOR_F1 VALUES (5, 'Google', 'Major', 'Tech');
INSERT INTO SPONSOR_F1 VALUES (6, 'BWT', 'Title', 'Water');
INSERT INTO SPONSOR_F1 VALUES (7, 'HP', 'Title', 'Tech');
INSERT INTO SPONSOR_F1 VALUES (8, 'Rolex', 'Global', 'Luxury');
INSERT INTO SPONSOR_F1 VALUES (9, 'Stake', 'Title', 'Betting');
INSERT INTO SPONSOR_F1 VALUES (10, 'MoneyGram', 'Title', 'Finance');

select * from sponsor_f1;


-- DONE ✅ 
INSERT INTO MODEL_VEHICUL_F1 VALUES (1, 'RB20', 'High Downforce', 350);
INSERT INTO MODEL_VEHICUL_F1 VALUES (2, 'W15', 'Balanced', 345);
INSERT INTO MODEL_VEHICUL_F1 VALUES (3, 'SF-24', 'High Speed Cornering', 348);
INSERT INTO MODEL_VEHICUL_F1 VALUES (4, 'MCL38', 'Efficient Drag', 346);
INSERT INTO MODEL_VEHICUL_F1 VALUES (5, 'AMR24', 'Medium Downforce', 342);
INSERT INTO MODEL_VEHICUL_F1 VALUES (6, 'A524', 'Low Drag', 340);
INSERT INTO MODEL_VEHICUL_F1 VALUES (7, 'FW46', 'Straight Line Speed', 352);
INSERT INTO MODEL_VEHICUL_F1 VALUES (8, 'VCARB 01', 'Technical', 338);
INSERT INTO MODEL_VEHICUL_F1 VALUES (9, 'C44', 'Balanced', 335);
INSERT INTO MODEL_VEHICUL_F1 VALUES (10, 'VF-24', 'Cornering', 330);

select * from model_vehicul_f1;


-- DONE ✅ 
INSERT INTO CIRCUIT_F1 VALUES (circuit_seq.NEXTVAL, 'Sakhir', 'Bahrain', 'Sakhir', 5.412, 15, 3);
INSERT INTO CIRCUIT_F1 VALUES (circuit_seq.NEXTVAL, 'Jeddah', 'Saudi Arabia', 'Jeddah', 6.174, 27, 3);
INSERT INTO CIRCUIT_F1 VALUES (circuit_seq.NEXTVAL, 'Albert Park', 'Australia', 'Melbourne', 5.278, 14, 4);
INSERT INTO CIRCUIT_F1 VALUES (circuit_seq.NEXTVAL, 'Suzuka', 'Japan', 'Suzuka', 5.807, 18, 1);
INSERT INTO CIRCUIT_F1 VALUES (circuit_seq.NEXTVAL, 'Shanghai', 'China', 'Shanghai', 5.451, 16, 2);
INSERT INTO CIRCUIT_F1 VALUES (circuit_seq.NEXTVAL, 'Miami', 'USA', 'Miami', 5.412, 19, 3);
INSERT INTO CIRCUIT_F1 VALUES (circuit_seq.NEXTVAL, 'Imola', 'Italy', 'Imola', 4.909, 19, 1);
INSERT INTO CIRCUIT_F1 VALUES (circuit_seq.NEXTVAL, 'Monaco', 'Monaco', 'Monte Carlo', 3.337, 19, 1);
INSERT INTO CIRCUIT_F1 VALUES (circuit_seq.NEXTVAL, 'Montreal', 'Canada', 'Montreal', 4.361, 14, 2);
INSERT INTO CIRCUIT_F1 VALUES (circuit_seq.NEXTVAL, 'Catalunya', 'Spain', 'Barcelona', 4.657, 14, 2);

select * from circuit_f1;

-- DONE ✅
INSERT INTO TIP_BILET_F1 VALUES (tip_bilet_seq.NEXTVAL, 'Bronze', 'NO');
INSERT INTO TIP_BILET_F1 VALUES (tip_bilet_seq.NEXTVAL, 'Silver', 'NO');
INSERT INTO TIP_BILET_F1 VALUES (tip_bilet_seq.NEXTVAL, 'Gold', 'NO');
INSERT INTO TIP_BILET_F1 VALUES (tip_bilet_seq.NEXTVAL, 'Platinum', 'NO');
INSERT INTO TIP_BILET_F1 VALUES (tip_bilet_seq.NEXTVAL, 'VIP', 'YES');
INSERT INTO TIP_BILET_F1 VALUES (tip_bilet_seq.NEXTVAL, 'Exclusive', 'YES');

select * from tip_bilet_f1;


-- DONE ✅ 
INSERT INTO ECHIPA_F1 VALUES (echipa_seq.NEXTVAL, 'Red Bull', 'UK', 600000000, 2005);
INSERT INTO ECHIPA_F1 VALUES (echipa_seq.NEXTVAL, 'Ferrari', 'Italy', 650000000, 1929);
INSERT INTO ECHIPA_F1 VALUES (echipa_seq.NEXTVAL, 'Mercedes', 'UK', 550000000, 2010);
INSERT INTO ECHIPA_F1 VALUES (echipa_seq.NEXTVAL, 'McLaren', 'UK', 450000000, 1963);
INSERT INTO ECHIPA_F1 VALUES (echipa_seq.NEXTVAL, 'Aston Martin', 'UK', 400000000, 2021);
INSERT INTO ECHIPA_F1 VALUES (echipa_seq.NEXTVAL, 'Alpine', 'UK', 350000000, 2021);
INSERT INTO ECHIPA_F1 VALUES (echipa_seq.NEXTVAL, 'Williams', 'UK', 250000000, 1977);
INSERT INTO ECHIPA_F1 VALUES (echipa_seq.NEXTVAL, 'Racing Bulls', 'Italy', 200000000, 2024);
INSERT INTO ECHIPA_F1 VALUES (echipa_seq.NEXTVAL, 'Sauber', 'Switzerland', 180000000, 1993);
INSERT INTO ECHIPA_F1 VALUES (echipa_seq.NEXTVAL, 'Haas', 'USA', 150000000, 2016);

select * from echipa_f1;


-- DONE ✅ 
INSERT INTO PILOT_F1 VALUES (pilot_seq.NEXTVAL, 'Verstappen', 'Max', TO_DATE('1990-01-26', 'YYYY-MM-DD'), 'NED', 2500, 3);
INSERT INTO PILOT_F1 VALUES (pilot_seq.NEXTVAL, 'Perez', 'Sergio', TO_DATE('1990-01-26', 'YYYY-MM-DD'), 'MEX', 1500, 0);
INSERT INTO PILOT_F1 VALUES (pilot_seq.NEXTVAL, 'Leclerc', 'Charles', TO_DATE('1997-10-16', 'YYYY-MM-DD'), 'MON', 1100, 0);
INSERT INTO PILOT_F1 VALUES (pilot_seq.NEXTVAL, 'Sainz', 'Carlos', TO_DATE('1994-09-01', 'YYYY-MM-DD'), 'ESP', 1000, 0);
INSERT INTO PILOT_F1 VALUES (pilot_seq.NEXTVAL, 'Hamilton', 'Lewis', TO_DATE('1985-01-07', 'YYYY-MM-DD'), 'GBR', 4639, 7);
INSERT INTO PILOT_F1 VALUES (pilot_seq.NEXTVAL, 'Russell', 'George', TO_DATE('1998-02-15', 'YYYY-MM-DD'), 'GBR', 494, 0);
INSERT INTO PILOT_F1 VALUES (pilot_seq.NEXTVAL, 'Norris', 'Lando', TO_DATE('1999-11-13', 'YYYY-MM-DD'), 'GBR', 691, 0);
INSERT INTO PILOT_F1 VALUES (pilot_seq.NEXTVAL, 'Piastri', 'Oscar', TO_DATE('2001-04-06', 'YYYY-MM-DD'), 'AUS', 120, 0);
INSERT INTO PILOT_F1 VALUES (pilot_seq.NEXTVAL, 'Alonso', 'Fernando', TO_DATE('1981-07-29', 'YYYY-MM-DD'), 'ESP', 2280, 2);
INSERT INTO PILOT_F1 VALUES (pilot_seq.NEXTVAL, 'Stroll', 'Lance', TO_DATE('1998-10-29', 'YYYY-MM-DD'), 'CAN', 280, 0);
INSERT INTO PILOT_F1 VALUES (pilot_seq.NEXTVAL, 'Gasly', 'Pierre', TO_DATE('1996-02-07', 'YYYY-MM-DD'), 'FRA', 400, 0);
INSERT INTO PILOT_F1 VALUES (pilot_seq.NEXTVAL, 'Ocon', 'Esteban', TO_DATE('1996-09-17', 'YYYY-MM-DD'), 'FRA', 430, 0);
INSERT INTO PILOT_F1 VALUES (pilot_seq.NEXTVAL, 'Albon', 'Alexander', TO_DATE('1996-03-23', 'YYYY-MM-DD'), 'THA', 240, 0);
INSERT INTO PILOT_F1 VALUES (pilot_seq.NEXTVAL, 'Sargeant', 'Logan', TO_DATE('2000-12-31', 'YYYY-MM-DD'), 'USA', 1, 0);
INSERT INTO PILOT_F1 VALUES (pilot_seq.NEXTVAL, 'Ricciardo', 'Daniel', TO_DATE('1989-07-01', 'YYYY-MM-DD'), 'AUS', 1320, 0);
INSERT INTO PILOT_F1 VALUES (pilot_seq.NEXTVAL, 'Tsunoda', 'Yuki', TO_DATE('2000-05-11', 'YYYY-MM-DD'), 'JPN', 70, 0);
INSERT INTO PILOT_F1 VALUES (pilot_seq.NEXTVAL, 'Bottas', 'Valtteri', TO_DATE('1989-08-28', 'YYYY-MM-DD'), 'FIN', 1797, 0);
INSERT INTO PILOT_F1 VALUES (pilot_seq.NEXTVAL, 'Zhou', 'Guanyu', TO_DATE('1999-05-30', 'YYYY-MM-DD'), 'CHN', 12, 0);
INSERT INTO PILOT_F1 VALUES (pilot_seq.NEXTVAL, 'Hulkenberg', 'Nico', TO_DATE('1987-08-19', 'YYYY-MM-DD'), 'GER', 540, 0);
INSERT INTO PILOT_F1 VALUES (pilot_seq.NEXTVAL, 'Magnussen', 'Kevin', TO_DATE('1992-10-05', 'YYYY-MM-DD'), 'DEN', 190, 0);

select * from pilot_f1;


-- DONE ✅ 
INSERT INTO ISTORIC_ECHIPA_PILOT VALUES (101, 1, 1,  TO_DATE('2025-01-01', 'YYYY-MM-DD'), TO_DATE('2029-01-01', 'YYYY-MM-DD'), 48200000);
INSERT INTO ISTORIC_ECHIPA_PILOT VALUES (102, 1, 2,  TO_DATE('2025-01-04', 'YYYY-MM-DD'), TO_DATE('2029-01-04', 'YYYY-MM-DD'), 15700000);
INSERT INTO ISTORIC_ECHIPA_PILOT VALUES (105, 2, 5,  TO_DATE('2025-01-08', 'YYYY-MM-DD'), TO_DATE('2028-01-08', 'YYYY-MM-DD'), 39100000);
INSERT INTO ISTORIC_ECHIPA_PILOT VALUES (106, 2, 6,  TO_DATE('2025-01-11', 'YYYY-MM-DD'), TO_DATE('2029-01-11', 'YYYY-MM-DD'), 7200000);
INSERT INTO ISTORIC_ECHIPA_PILOT VALUES (103, 3, 3,  TO_DATE('2025-01-15', 'YYYY-MM-DD'), TO_DATE('2029-01-15', 'YYYY-MM-DD'), 26400000);
INSERT INTO ISTORIC_ECHIPA_PILOT VALUES (104, 3, 4,  TO_DATE('2025-01-18', 'YYYY-MM-DD'), TO_DATE('2028-01-18', 'YYYY-MM-DD'), 13200000);
INSERT INTO ISTORIC_ECHIPA_PILOT VALUES (107, 4, 7,  TO_DATE('2025-01-22', 'YYYY-MM-DD'), TO_DATE('2028-01-22', 'YYYY-MM-DD'), 21800000);
INSERT INTO ISTORIC_ECHIPA_PILOT VALUES (108, 4, 8,  TO_DATE('2025-01-25', 'YYYY-MM-DD'), TO_DATE('2029-01-25', 'YYYY-MM-DD'), 5800000);
INSERT INTO ISTORIC_ECHIPA_PILOT VALUES (109, 5, 9,  TO_DATE('2025-01-29', 'YYYY-MM-DD'), TO_DATE('2029-01-29', 'YYYY-MM-DD'), 19400000);
INSERT INTO ISTORIC_ECHIPA_PILOT VALUES (110, 5, 10, TO_DATE('2025-02-01', 'YYYY-MM-DD'), TO_DATE('2028-02-01', 'YYYY-MM-DD'), 3000000);
INSERT INTO ISTORIC_ECHIPA_PILOT VALUES (111, 6, 11, TO_DATE('2025-02-05', 'YYYY-MM-DD'), TO_DATE('2029-02-05', 'YYYY-MM-DD'), 5300000);
INSERT INTO ISTORIC_ECHIPA_PILOT VALUES (112, 6, 12, TO_DATE('2025-02-08', 'YYYY-MM-DD'), TO_DATE('2028-02-08', 'YYYY-MM-DD'), 7400000);
INSERT INTO ISTORIC_ECHIPA_PILOT VALUES (113, 7, 13, TO_DATE('2025-02-12', 'YYYY-MM-DD'), TO_DATE('2028-02-12', 'YYYY-MM-DD'), 4200000);
INSERT INTO ISTORIC_ECHIPA_PILOT VALUES (114, 7, 14, TO_DATE('2025-02-15', 'YYYY-MM-DD'), TO_DATE('2029-02-15', 'YYYY-MM-DD'), 1900000);
INSERT INTO ISTORIC_ECHIPA_PILOT VALUES (115, 8, 15, TO_DATE('2025-02-19', 'YYYY-MM-DD'), TO_DATE('2028-02-19', 'YYYY-MM-DD'), 8600000);
INSERT INTO ISTORIC_ECHIPA_PILOT VALUES (116, 8, 16, TO_DATE('2025-02-22', 'YYYY-MM-DD'), TO_DATE('2029-02-22', 'YYYY-MM-DD'), 2700000);
INSERT INTO ISTORIC_ECHIPA_PILOT VALUES (117, 9, 17, TO_DATE('2025-02-26', 'YYYY-MM-DD'), TO_DATE('2028-02-26', 'YYYY-MM-DD'), 11800000);
INSERT INTO ISTORIC_ECHIPA_PILOT VALUES (118, 9, 18, TO_DATE('2025-03-01', 'YYYY-MM-DD'), TO_DATE('2029-03-01', 'YYYY-MM-DD'), 3400000);
INSERT INTO ISTORIC_ECHIPA_PILOT VALUES (119, 10, 19, TO_DATE('2025-03-05', 'YYYY-MM-DD'), TO_DATE('2028-03-05', 'YYYY-MM-DD'), 5600000);
INSERT INTO ISTORIC_ECHIPA_PILOT VALUES (120, 10, 20, TO_DATE('2025-03-08', 'YYYY-MM-DD'), TO_DATE('2029-03-08', 'YYYY-MM-DD'), 9100000);


select * from istoric_echipa_pilot;


-- DONE ✅ 
INSERT INTO VEHICUL_F1 (id_echipa, id_model, greutate, pneuri, pret, data_inspectie)  VALUES (1, 1, 794, 'Pirelli', 15500000.00, TO_DATE('2025-01-12', 'YYYY-MM-DD'));
INSERT INTO VEHICUL_F1 (id_echipa, id_model, greutate, pneuri, pret, data_inspectie)  VALUES (2, 2, 792, 'Michelin', 15200000.00, TO_DATE('2025-04-27', 'YYYY-MM-DD'));
INSERT INTO VEHICUL_F1 (id_echipa, id_model, greutate, pneuri, pret, data_inspectie)  VALUES (3, 3, 780, 'Bridgestone', 15400000.00, TO_DATE('2025-02-03', 'YYYY-MM-DD'));
INSERT INTO VEHICUL_F1 (id_echipa, id_model, greutate, pneuri, pret, data_inspectie)  VALUES (4, 4, 783, 'Goodyear', 14800000.00, TO_DATE('2025-06-18', 'YYYY-MM-DD'));
INSERT INTO VEHICUL_F1 (id_echipa, id_model, greutate, pneuri, pret, data_inspectie)  VALUES (5, 5, 790, 'Pirelli', 14200000.00, TO_DATE('2025-07-29', 'YYYY-MM-DD'));
INSERT INTO VEHICUL_F1 (id_echipa, id_model, greutate, pneuri, pret, data_inspectie)  VALUES (6, 6, 799, 'Michelin', 13500000.00, TO_DATE('2025-03-11', 'YYYY-MM-DD'));
INSERT INTO VEHICUL_F1 (id_echipa, id_model, greutate, pneuri, pret, data_inspectie)  VALUES (7, 7, 791, 'Continental', 12500000.00, TO_DATE('2025-09-22', 'YYYY-MM-DD'));
INSERT INTO VEHICUL_F1 (id_echipa, id_model, greutate, pneuri, pret, data_inspectie)  VALUES (8, 8, 787, 'Michelin', 12800000.00, TO_DATE('2025-02-14', 'YYYY-MM-DD'));
INSERT INTO VEHICUL_F1 (id_echipa, id_model, greutate, pneuri, pret, data_inspectie)  VALUES (9, 9, 788, 'Goodyear', 11900000.00, TO_DATE('2025-08-03', 'YYYY-MM-DD'));
INSERT INTO VEHICUL_F1 (id_echipa, id_model, greutate, pneuri, pret, data_inspectie)  VALUES (10, 10, 795, 'Continental', 11000000.00, TO_DATE('2025-11-19', 'YYYY-MM-DD'));


select * from vehicul_f1;


-- DONE ✅
INSERT INTO CURSA_F1 VALUES (1, 1, 'Grand Prix', TO_DATE('2025-01-05', 'YYYY-MM-DD'), 90, '1:31.447', 'Clear', 'Finished');
INSERT INTO CURSA_F1 VALUES (2, 2, 'Qualifying', TO_DATE('2025-02-17', 'YYYY-MM-DD'), 60, '1:27.472', 'Clear', 'Finished');
INSERT INTO CURSA_F1 VALUES (3, 3, 'Practice', TO_DATE('2025-03-11', 'YYYY-MM-DD'), 60, '1:19.813', 'Sunny', 'Finished');
INSERT INTO CURSA_F1 VALUES (4, 4, 'Grand Prix', TO_DATE('2025-04-28', 'YYYY-MM-DD'), 45, '1:33.706', 'Rain', 'Suspended');
INSERT INTO CURSA_F1 VALUES (5, 5, 'Sprint', TO_DATE('2025-05-09', 'YYYY-MM-DD'), 35, '1:32.238', 'Cloudy', 'Finished');
INSERT INTO CURSA_F1 VALUES (6, 6, 'Grand Prix', TO_DATE('2025-06-03', 'YYYY-MM-DD'), 94, '1:27.382', 'Sunny', 'Finished');
INSERT INTO CURSA_F1 VALUES (7, 7, 'Practice', TO_DATE('2025-07-14', 'YYYY-MM-DD'), 0, 'N/A', 'Storm', 'Cancelled');
INSERT INTO CURSA_F1 VALUES (8, 8, 'Grand Prix', TO_DATE('2025-08-19', 'YYYY-MM-DD'), 120, '1:10.232', 'Clear', 'Finished');
INSERT INTO CURSA_F1 VALUES (9, 9, 'Grand Prix', TO_DATE('2025-09-07', 'YYYY-MM-DD'), 95, '1:11.876', 'Rain', 'Planned');
INSERT INTO CURSA_F1 VALUES (10, 10, 'Sprint', TO_DATE('2025-10-21', 'YYYY-MM-DD'), 30, '1:13.200', 'Sunny', 'Planned');


select * from cursa_f1;


-- DONE ✅
INSERT INTO BILET_F1 (id_cursa, id_tip_bilet, loc_tribuna, loc_rand, loc_numar, data_achizitie, stare) VALUES (1, 1, 'A1', 1, 1, TO_DATE('2024-02-14', 'YYYY-MM-DD'), 'Sold');
INSERT INTO BILET_F1 (id_cursa, id_tip_bilet, loc_tribuna, loc_rand, loc_numar, data_achizitie, stare) VALUES (2, 2, 'T3', 2, 2, TO_DATE('2024-03-05', 'YYYY-MM-DD'), 'Sold');
INSERT INTO BILET_F1 (id_cursa, id_tip_bilet, loc_tribuna, loc_rand, loc_numar, data_achizitie, stare) VALUES (3, 3, 'B3', 3, 3, TO_DATE('2024-01-22', 'YYYY-MM-DD'), 'Sold');
INSERT INTO BILET_F1 (id_cursa, id_tip_bilet, loc_tribuna, loc_rand, loc_numar, data_achizitie, stare) VALUES (4, 4, 'C2', 4, 4, TO_DATE('2024-04-11', 'YYYY-MM-DD'), 'Sold');
INSERT INTO BILET_F1 (id_cursa, id_tip_bilet, loc_tribuna, loc_rand, loc_numar, data_achizitie, stare) VALUES (5, 5, 'D5', 5, 5, TO_DATE('2024-02-27', 'YYYY-MM-DD'), 'Sold');
INSERT INTO BILET_F1 (id_cursa, id_tip_bilet, loc_tribuna, loc_rand, loc_numar, data_achizitie, stare) VALUES (6, 6, 'E1', 6, 6, TO_DATE('2024-03-29', 'YYYY-MM-DD'), 'Sold');
INSERT INTO BILET_F1 (id_cursa, id_tip_bilet, loc_tribuna, loc_rand, loc_numar, data_achizitie, stare) VALUES (7, 2, 'F4', 7, 7, TO_DATE('2024-05-03', 'YYYY-MM-DD'), 'Sold');
INSERT INTO BILET_F1 (id_cursa, id_tip_bilet, loc_tribuna, loc_rand, loc_numar, data_achizitie, stare) VALUES (8, 3, 'G2', 8, 8, TO_DATE('2024-06-18', 'YYYY-MM-DD'), 'Sold');
INSERT INTO BILET_F1 (id_cursa, id_tip_bilet, loc_tribuna, loc_rand, loc_numar, data_achizitie, stare) VALUES (9, 4, 'H3', 9, 9, TO_DATE('2024-07-09', 'YYYY-MM-DD'), 'Sold');
INSERT INTO BILET_F1 (id_cursa, id_tip_bilet, loc_tribuna, loc_rand, loc_numar, data_achizitie, stare) VALUES (10, 5, 'J1', 10, 10, TO_DATE('2024-08-25', 'YYYY-MM-DD'), 'Valid');

select * from bilet_f1;

-- DONE ✅
INSERT INTO ECHIPA_SPONSOR_F1 VALUES (1, 1, 100000000.00, 'YES');
INSERT INTO ECHIPA_SPONSOR_F1  VALUES (2, 2, 75000000.00, 'YES');
INSERT INTO ECHIPA_SPONSOR_F1  VALUES (3, 3, 40000000.00, 'YES');
INSERT INTO ECHIPA_SPONSOR_F1  VALUES (4, 4, 30000000.00, 'YES');
INSERT INTO ECHIPA_SPONSOR_F1  VALUES (5, 5, 60000000.00, 'YES');
INSERT INTO ECHIPA_SPONSOR_F1  VALUES (6, 6, 35000000.00, 'YES');
INSERT INTO ECHIPA_SPONSOR_F1  VALUES (7, 8, 20000000.00, 'YES');
INSERT INTO ECHIPA_SPONSOR_F1  VALUES (8, 8, 15000000.00, 'YES');
INSERT INTO ECHIPA_SPONSOR_F1  VALUES (9, 9, 45000000.00, 'YES');
INSERT INTO ECHIPA_SPONSOR_F1  VALUES (10, 10, 25000000.00, 'YES');

select * from echipa_sponsor_f1;


--- DONE ✅
INSERT INTO PILOT_CURSA_F1  VALUES (1, 1, 1, 1);
INSERT INTO PILOT_CURSA_F1  VALUES (2, 1, 5, 2);
INSERT INTO PILOT_CURSA_F1  VALUES (3, 1, 2, 4);
INSERT INTO PILOT_CURSA_F1  VALUES (4, 1, 4, 3);
INSERT INTO PILOT_CURSA_F1  VALUES (5, 1, 9, 7);
INSERT INTO PILOT_CURSA_F1  VALUES (6, 1, 3, 5);
INSERT INTO PILOT_CURSA_F1  VALUES (7, 1, 7, 6);
INSERT INTO PILOT_CURSA_F1  VALUES (8, 1, 8, 8);
INSERT INTO PILOT_CURSA_F1  VALUES (9, 1, 6, 9);
INSERT INTO PILOT_CURSA_F1  VALUES (10, 1, 12, 10);


select * from pilot_cursa_f1;



---------------------------------------------------------------------------------------------


-- 6

-- Sa se realizeze o procedura care analizeaza ultimele cinci echipe infiintate, 
-- utilizand un Varray pentru nume, un tabel imbricat pentru bugete si un tabel indexat
-- pentru numarul de sponsori activi, cu scopul de a genera un raport de sustenabilitate comerciala.

CREATE OR REPLACE PROCEDURE p_analiza_echipe IS
    TYPE varray_echipe IS VARRAY(5) OF VARCHAR(100);
    lista_echipe varray_echipe := varray_echipe();

    TYPE tbl_bugete IS TABLE OF NUMBER;
    bugete tbl_bugete := tbl_bugete();

    TYPE tbl_nr_sponsori IS TABLE OF NUMBER INDEX BY VARCHAR(100);
    nr_sponsori tbl_nr_sponsori;

BEGIN
    SELECT nume BULK COLLECT INTO lista_echipe
    FROM ECHIPA_F1
    ORDER BY an_infiintare DESC
    FETCH FIRST 5 ROWS ONLY;

    bugete.EXTEND(lista_echipe.COUNT);
    FOR i IN 1 .. lista_echipe.COUNT LOOP
        SELECT buget INTO bugete(i)
        FROM ECHIPA_F1
        WHERE nume = lista_echipe(i);
        
    END LOOP;

    FOR i IN 1 .. lista_echipe.COUNT LOOP
        SELECT COUNT(*) INTO nr_sponsori(lista_echipe(i))
        FROM ECHIPA_SPONSOR_F1 ES
        JOIN ECHIPA_F1 E ON E.id_echipa = ES.id_echipa
        WHERE E.nume = lista_echipe(i) AND ES.status_activ = 'YES';
    END LOOP;

    DBMS_OUTPUT.PUT_LINE('--- Primele 5 echipe cele mai noi infiintate ---');
    DBMS_OUTPUT.PUT_LINE('');
    FOR i IN 1 .. lista_echipe.COUNT LOOP
        DBMS_OUTPUT.PUT_LINE('Echipa: ' || lista_echipe(i));
        DBMS_OUTPUT.PUT_LINE(' - Buget: ' || bugete(i));
        DBMS_OUTPUT.PUT_LINE(' - Numar sponsori activi: ' || nr_sponsori(lista_echipe(i)));
        DBMS_OUTPUT.PUT_LINE('---------------------------');
    END LOOP;

END;

BEGIN
    p_analiza_echipe;
END;


-- 7
-- Departamentul administrativ al FIA doreste monitorizarea situatiei contractuale a pilotilor din campionatul curent. 
-- Pentru o organizare eficienta, este necesara vizualizarea pilotilor grupati in functie de echipa la care sunt legitimati.
-- Sa se realizeze un subprogram stocat independent (procedura) care sa genereze un raport al contractelor active. 


CREATE OR REPLACE PROCEDURE p_raport_piloti_activi IS
    CURSOR cursor_piloti_activi (id_echipa_importata NUMBER) 
    IS
        SELECT P.nume, P.prenume, I.salariu, I.data_final
        FROM ISTORIC_ECHIPA_PILOT I
        JOIN PILOT_F1 P ON I.id_pilot = P.id_pilot
        WHERE I.id_echipa = id_echipa_importata AND I.data_final >= SYSDATE;

    nume_pilot      PILOT_F1.nume%TYPE;
    prenume_pilot   PILOT_F1.prenume%TYPE;
    salariu_angajat ISTORIC_ECHIPA_PILOT.salariu%TYPE;
    data_expirare   ISTORIC_ECHIPA_PILOT.data_final%TYPE;

BEGIN
    DBMS_OUTPUT.PUT_LINE('=== PILOTI CU CONTRACTE ACTIVE ===');
    DBMS_OUTPUT.PUT_LINE('');

    FOR echipa_curenta IN (SELECT id_echipa, nume FROM ECHIPA_F1 ORDER BY nume) LOOP
        DBMS_OUTPUT.PUT_LINE('Echipa: ' || echipa_curenta.nume);

        OPEN cursor_piloti_activi(echipa_curenta.id_echipa);
        
        LOOP
            FETCH cursor_piloti_activi INTO nume_pilot, prenume_pilot, salariu_angajat, data_expirare;
            EXIT WHEN cursor_piloti_activi%NOTFOUND;
            
            DBMS_OUTPUT.PUT_LINE('-> ' || nume_pilot || ' ' || prenume_pilot || ' | Salariu ' || salariu_angajat || ' EURO | ' || '(Expira la: ' || TO_CHAR(data_expirare, 'DD.MM.YYYY') || ')');
        END LOOP;

        IF cursor_piloti_activi%ROWCOUNT=0 THEN
            DBMS_OUTPUT.PUT_LINE('-> (Niciun pilot activ gasit)');
        END IF;

        CLOSE cursor_piloti_activi;
        DBMS_OUTPUT.PUT_LINE('----------------------------------');
        
    END LOOP;
END;

BEGIN
    p_raport_piloti_activi;
END;


-- 8

-- Mecanicii fiecarei echipe au nevoie de o metoda rapida pentru a identifica modelul de maasina care detine recordul de viteza din garajul lor 
-- Se va realiza o functie care primeste codul echipei si returneaza denumirea celui mai rapid model, interogand simultan tabelele ECHIPA_F1, VEHICUL_F1 si MODEL_VEHICUL_F1 
-- Inspectorii tehnici vor folosi acest subprogram pentru a valida datele, functia gestionand exceptiile pentru coduri de echipa inexistente, 
-- lipsa mașinilor din inventar sau existenta mai multor modele cu aceeasi viteza maxima.

CREATE OR REPLACE FUNCTION f_model_cel_mai_rapid_echipa (
    id_echipa_cautata IN NUMBER
) 
RETURN VARCHAR
IS
    nume_model MODEL_VEHICUL_F1.nume%TYPE;
    exista_echipa NUMBER;

    ECHIPA_INEXISTENTA EXCEPTION;
BEGIN
    SELECT COUNT(*) INTO exista_echipa
    FROM ECHIPA_F1
    WHERE id_echipa = id_echipa_cautata;

    IF exista_echipa = 0 THEN
        RAISE ECHIPA_INEXISTENTA;
    END IF;

    SELECT DISTINCT MV.nume INTO nume_model
    FROM ECHIPA_F1 E
    JOIN VEHICUL_F1 V ON E.id_echipa = V.id_echipa
    JOIN MODEL_VEHICUL_F1 MV ON V.id_model = MV.id_model
    WHERE E.id_echipa = id_echipa_cautata AND MV.viteza_maxima = (
                SELECT MAX(MV2.viteza_maxima)
                FROM VEHICUL_F1 V2
                JOIN MODEL_VEHICUL_F1 MV2 ON V2.id_model = MV2.id_model
                WHERE V2.id_echipa = id_echipa_cautata
                );

    RETURN nume_model;

    EXCEPTION
        WHEN ECHIPA_INEXISTENTA THEN
            DBMS_OUTPUT.PUT_LINE('Eroare: ID-ul ' || id_echipa_cautata || ' nu corespunde niciunei echipe.');
            RETURN NULL;
    
        WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('Eroare: Echipa exista, dar nu are niciun vehicul sau model asociat.');
            RETURN NULL;
    
        WHEN TOO_MANY_ROWS THEN
            DBMS_OUTPUT.PUT_LINE('Eroare: Exista mai multe modele diferite care ating aceeasi viteza maxima.');
            RETURN NULL;
    
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('Eroare neprevazuta: ' || SQLERRM);
            RETURN NULL;
END;

BEGIN
    DBMS_OUTPUT.PUT_LINE('Model cel mai rapid: ' || f_model_cel_mai_rapid_echipa(1));
END;

BEGIN
    DBMS_OUTPUT.PUT_LINE(f_model_cel_mai_rapid_echipa(9999));
END; 


INSERT INTO MODEL_VEHICUL_F1 VALUES (99, 'RB20', 'High Downforce', 350);
INSERT INTO VEHICUL_F1 (id_echipa, id_model, greutate, pneuri, pret, data_inspectie) VALUES (1, 99, 798, 'Pirelli', 15000000, SYSDATE);

BEGIN
    DBMS_OUTPUT.PUT_LINE(f_model_cel_mai_rapid_echipa(1));
END;

rollback;

select * from model_vehicul_f1;
select * from vehicul_f1;


-- 9 

CREATE OR REPLACE PROCEDURE p_venit_anual_pilot (
    cod_pilot_intrare IN INT,
    an_ales           IN NUMBER
) IS
    suma_totala_calculata NUMBER(15,2);
    numar_verificare      NUMBER;
    
    nume_pilot            VARCHAR2(50);
    prenume_pilot         VARCHAR2(50);

    PILOT_NEIDENTIFICAT   EXCEPTION;
    FARA_CURSE_IN_AN      EXCEPTION;
    FARA_CONTRACT_IN_AN   EXCEPTION;
BEGIN
    BEGIN
        SELECT nume, prenume INTO nume_pilot, prenume_pilot
        FROM PILOT_F1
        WHERE id_pilot = cod_pilot_intrare;
        
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                RAISE PILOT_NEIDENTIFICAT;
    END;

    SELECT COUNT(*) INTO numar_verificare
    FROM PILOT_CURSA_F1 PC
    JOIN CURSA_F1 c ON PC.id_cursa = C.id_cursa
    WHERE pc.id_pilot = cod_pilot_intrare AND EXTRACT(YEAR FROM c.data_cursa) = an_ales;

    IF numar_verificare = 0 THEN
        RAISE FARA_CURSE_IN_AN;
    END IF;

    SELECT COUNT(*) INTO numar_verificare
    FROM ISTORIC_ECHIPA_PILOT
    WHERE id_pilot = cod_pilot_intrare AND an_ales BETWEEN EXTRACT(YEAR FROM data_inceput) AND EXTRACT(YEAR FROM data_final);

    IF numar_verificare = 0 THEN
        RAISE FARA_CONTRACT_IN_AN;
    END IF;

    SELECT
        NVL(MAX(H.salariu), 0) + NVL(SUM(DISTINCT ES.contributie_financiara), 0) +
        NVL(SUM(
            CASE TB.categorie
                WHEN 'Bronze'     THEN 100
                WHEN 'Silver'     THEN 200
                WHEN 'Gold'       THEN 300
                WHEN 'Platinum'   THEN 500
                WHEN 'VIP'        THEN 800
                WHEN 'Exclusive'  THEN 1200
                ELSE 0
            END
        ), 0)
    INTO suma_totala_calculata
    FROM PILOT_F1 P
    LEFT JOIN ISTORIC_ECHIPA_PILOT H ON P.id_pilot = H.id_pilot AND an_ales BETWEEN EXTRACT(YEAR FROM H.data_inceput) AND EXTRACT(YEAR FROM H.data_final)
    LEFT JOIN ECHIPA_SPONSOR_F1 ES ON H.id_echipa = ES.id_echipa
    JOIN PILOT_CURSA_F1 PC ON P.id_pilot = PC.id_pilot
    JOIN CURSA_F1 C ON PC.id_cursa = C.id_cursa AND EXTRACT(YEAR FROM C.data_cursa) = an_ales
    LEFT JOIN BILET_F1 B ON C.id_cursa = B.id_cursa
    LEFT JOIN TIP_BILET_F1 TB ON B.id_tip_bilet = TB.id_tip_bilet
    WHERE p.id_pilot = cod_pilot_intrare;

    DBMS_OUTPUT.PUT_LINE('Raport financiar pentru: ' || prenume_pilot || ' ' || nume_pilot);
    DBMS_OUTPUT.PUT_LINE('Venitul total in anul ' || an_ales || ' este: ' || suma_totala_calculata || ' EUR');

    EXCEPTION
        WHEN PILOT_NEIDENTIFICAT THEN
            DBMS_OUTPUT.PUT_LINE('Eroare: Pilotul cu ID ' || cod_pilot_intrare || ' nu exista.');
    
        WHEN FARA_CURSE_IN_AN THEN
            DBMS_OUTPUT.PUT_LINE('Eroare: Pilotul ' || prenume_pilot || ' ' || nume_pilot || 
                                 ' nu a participat la nicio cursa in anul ' || an_ales);
    
        WHEN FARA_CONTRACT_IN_AN THEN
            DBMS_OUTPUT.PUT_LINE('Atentie: ' || prenume_pilot || ' ' || nume_pilot || ' nu a avut contract activ in ' || an_ales || '. Venitul provine doar din bilete.');
    
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('Eroare neprevazuta: ' || SQLERRM);
END;

BEGIN
    DBMS_OUTPUT.PUT_LINE('--- Test 1: Succes (Date Valide) ---');
    p_venit_anual_pilot(1, 2025);
END;

BEGIN
    DBMS_OUTPUT.PUT_LINE(CHR(10) || '--- Test 2: Pilot Inexistent ---');
    p_venit_anual_pilot(999, 2025);
END;

BEGIN
    DBMS_OUTPUT.PUT_LINE(CHR(10) || '--- Test 3: An fara participare la curse ---');
    p_venit_anual_pilot(3, 2024);
END;

-- 10

-- odata ce masinile intra in regim de calificare sau cursa, 
-- echipele nu mai au voie sa faca modificari tehnice


CREATE OR REPLACE TRIGGER trg_restrictie_modificari_masini
BEFORE INSERT OR UPDATE OR DELETE ON VEHICUL_F1
DECLARE
    stare_cursa   VARCHAR(20); 
    nume_circuit  VARCHAR(100);
BEGIN
    stare_cursa := 'Nicio Cursa';
    nume_circuit := 'Nespecificat';

    BEGIN
        SELECT C.status, CIR.nume  INTO stare_cursa, nume_circuit
        FROM CURSA_F1 C
        JOIN CIRCUIT_F1 CIR ON C.id_circuit = CIR.id_circuit
        WHERE TRUNC(C.data_cursa) = TRUNC(SYSDATE)
        AND ROWNUM = 1;
        
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                NULL;
    END;

    IF stare_cursa IN ('In Progress', 'Suspended') THEN
        RAISE_APPLICATION_ERROR(-20001, 'BLOCAJ: Cursa de pe circuitul ' || nume_circuit || ' este ' || stare_cursa || '. Modificarile sunt interzise!');
    ELSIF stare_cursa = 'Planned' THEN
        IF DELETING THEN
            RAISE_APPLICATION_ERROR(-20002, 'RESTRICTIE: Nu puteti sterge vehiculele in ziua cursei ' || nume_circuit);
        END IF;
        DBMS_OUTPUT.PUT_LINE('Verificare: Actualizarile sunt permise pentru pregatirea cursei ' || nume_circuit);
    
    ELSE
        DBMS_OUTPUT.PUT_LINE('Sistem deschis: Nu exista restrictii active pentru vehicule astazi.');
    END IF;
END;

INSERT INTO CURSA_F1 (id_cursa, id_circuit, tip_cursa, data_cursa, status) VALUES (99, 1, 'Grand Prix', SYSDATE, 'In Progress');

UPDATE VEHICUL_F1 
SET greutate = 850 
WHERE id_vehicul = 1;
-- REZULTAT: Eroare ORA-20020: "ALERTA: Modificarile sunt interzise! Cursa de pe Sakhir este In Progress


UPDATE CURSA_F1 
SET status = 'Planned' 
WHERE id_cursa = 99;

DELETE FROM VEHICUL_F1 
WHERE id_vehicul = 1;
-- REZULTAT: Eroare ORA-20021: "STOP: Nu se pot elimina vehicule in ziua cursei programate la Sakhir"

-- Marcăm cursa de azi ca fiind terminată 
UPDATE CURSA_F1 
SET status = 'Finished' 
WHERE id_cursa = 99;

UPDATE VEHICUL_F1 
SET pneuri = 'Soft' 
WHERE id_vehicul = 1;
-- REZULTAT: "1 row updated." 
-- Mesaj consolă: "Acces Liber: Nu sunt restrictii tehnice active astazi."

-- 11

---

CREATE OR REPLACE TRIGGER trg_control_vanzari_bilete
BEFORE INSERT OR UPDATE ON BILET_F1
FOR EACH ROW
DECLARE
    stare_actuală_cursă  VARCHAR2(20);
    tipul_evenimentului  VARCHAR2(50);
    nume_traseu          VARCHAR2(100);
    permite_pitstop      VARCHAR2(3);
BEGIN
    SELECT c.status, c.tip_cursa, cir.nume  INTO stare_actuală_cursă, tipul_evenimentului, nume_traseu
    FROM CURSA_F1 c
    JOIN CIRCUIT_F1 cir ON c.id_circuit = cir.id_circuit
    WHERE c.id_cursa = :NEW.id_cursa;

    SELECT acces_pitstop INTO permite_pitstop
    FROM TIP_BILET_F1
    WHERE id_tip_bilet = :NEW.id_tip_bilet;

    IF :NEW.stare = 'SOLD' AND stare_actuală_cursă IN ('Cancelled', 'Suspended', 'Finished') THEN
        RAISE_APPLICATION_ERROR(-20003, 'EROARE VÂNZARE: Cursa de la ' || nume_traseu || 
            ' este deja ' || stare_actuală_cursă || '. Nu se mai pot emite bilete!');
    END IF;

    IF tipul_evenimentului = 'Test Session' AND permite_pitstop = 'YES' THEN
        RAISE_APPLICATION_ERROR(-20004, 'RESTRICȚIE SECURITATE: Accesul la pitstop este interzis în timpul sesiunilor de tip ' || tipul_evenimentului);
    END IF;

    DBMS_OUTPUT.PUT_LINE('Bilet validat pentru circuitul: ' || nume_traseu);
END;


----
---

----------------------

CREATE OR REPLACE PACKAGE pachet_contracte_active IS
    -- Record pentru a retine numarul de piloti activi si un indicator de schimbare
    TYPE info_echipa IS RECORD(numar_activ NUMBER, a_fost_modificat NUMBER);
    TYPE colectie_active IS TABLE OF info_echipa INDEX BY PLS_INTEGER;
    
    inventar_active colectie_active;
END;

CREATE OR REPLACE TRIGGER trg_active_initializare
BEFORE INSERT OR UPDATE OF id_echipa, data_inceput, data_final ON ISTORIC_ECHIPA_PILOT
BEGIN
    -- Resetam memoria pachetului
    pachet_contracte_active.inventar_active.DELETE;
    
    -- Numaram doar contractele care sunt VALIDE astazi
    FOR r IN (SELECT id_echipa, COUNT(*) as total 
              FROM ISTORIC_ECHIPA_PILOT 
              WHERE TRUNC(SYSDATE) BETWEEN data_inceput AND data_final
              GROUP BY id_echipa) LOOP
        pachet_contracte_active.inventar_active(r.id_echipa).numar_activ := r.total;
        pachet_contracte_active.inventar_active(r.id_echipa).a_fost_modificat := 0;
    END LOOP;
END;


CREATE OR REPLACE TRIGGER trg_active_verificare_linie
BEFORE INSERT OR UPDATE OF id_echipa, data_inceput, data_final ON ISTORIC_ECHIPA_PILOT
FOR EACH ROW
BEGIN
    -- Verificam daca noul contract (sau cel modificat) este activ astazi
    IF TRUNC(SYSDATE) BETWEEN :NEW.data_inceput AND :NEW.data_final THEN
        
        -- Initializam echipa in memorie daca nu exista
        IF NOT pachet_contracte_active.inventar_active.EXISTS(:NEW.id_echipa) THEN
            pachet_contracte_active.inventar_active(:NEW.id_echipa).numar_activ := 0;
        END IF;

        -- Incrementam numarul de piloti activi
        pachet_contracte_active.inventar_active(:NEW.id_echipa).numar_activ := pachet_contracte_active.inventar_active(:NEW.id_echipa).numar_activ + 1;
        pachet_contracte_active.inventar_active(:NEW.id_echipa).a_fost_modificat := 1;

        -- Blocaj imediat daca se depaseste limita de 3 piloti activi
        IF pachet_contracte_active.inventar_active(:NEW.id_echipa).numar_activ > 3 THEN
            RAISE_APPLICATION_ERROR(-20005, 'LIMITA ATINSA: Echipa ' || :NEW.id_echipa || ' are deja 3 piloti ACTIVI astazi. Nu puteti adauga inca unul!');
        END IF;
    END IF;

    -- Daca modificam un contract care era activ, scadem din vechea echipa
    IF UPDATING AND TRUNC(SYSDATE) BETWEEN :OLD.data_inceput AND :OLD.data_final THEN
         IF pachet_contracte_active.inventar_active.EXISTS(:OLD.id_echipa) THEN
            pachet_contracte_active.inventar_active(:OLD.id_echipa).numar_activ := pachet_contracte_active.inventar_active(:OLD.id_echipa).numar_activ - 1;
         END IF;
    END IF;
END;


CREATE OR REPLACE TRIGGER trg_active_audit_final
AFTER INSERT OR UPDATE OF id_echipa, data_inceput, data_final ON ISTORIC_ECHIPA_PILOT
DECLARE
    cheie NUMBER;
BEGIN
    cheie := pachet_contracte_active.inventar_active.FIRST;
    
    WHILE cheie IS NOT NULL LOOP
        IF pachet_contracte_active.inventar_active(cheie).a_fost_modificat = 1 AND pachet_contracte_active.inventar_active(cheie).numar_activ > 3 THEN
            RAISE_APPLICATION_ERROR(-20006, 'REGULAMENT F1: In urma modificarilor, echipa ' || cheie || ' a ajuns la ' || pachet_contracte_active.inventar_active(cheie).numar_activ || ' piloti activi. Maximul permis este 3!');
        END IF;
        
        cheie := pachet_contracte_active.inventar_active.NEXT(cheie);
    END LOOP;
END;


-- 12

CREATE TABLE AUDIT_LDD_F1 (
    id_audit       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilizator     VARCHAR(50),
    eveniment      VARCHAR(50),
    tip_obiect     VARCHAR(50),
    nume_obiect    VARCHAR(100),
    data_ora       DATE,
    status         VARCHAR(20)
);

CREATE OR REPLACE PROCEDURE logheaza_eveniment_ldd (
    nume_utilizator VARCHAR2, 
    tip_ev          VARCHAR2, 
    tip_obj         VARCHAR2, 
    nume_obj        VARCHAR2, 
    stare           VARCHAR2
) 
IS
    PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
    INSERT INTO AUDIT_LDD_F1 (utilizator, eveniment, tip_obiect, nume_obiect, data_ora, status) VALUES (nume_utilizator, tip_ev, tip_obj, nume_obj, SYSDATE, stare);
    COMMIT;
END;

CREATE OR REPLACE TRIGGER trg_control_si_audit_f1
BEFORE CREATE OR ALTER OR DROP ON SCHEMA
DECLARE
    eveniment      VARCHAR(50);
    nume_obiect    VARCHAR(100);
    tip_obiect     VARCHAR(50);
    utilizator     VARCHAR(50);
BEGIN
    eveniment   := SYSEVENT;
    nume_obiect := SYS.DICTIONARY_OBJ_NAME;
    tip_obiect  := SYS.DICTIONARY_OBJ_TYPE;
    utilizator  := SYS.LOGIN_USER;

    IF eveniment = 'CREATE' AND tip_obiect = 'TABLE' THEN
        IF UPPER(nume_obiect) NOT LIKE '%_F1' THEN
            logheaza_eveniment_ldd(utilizator, eveniment, tip_obiect, nume_obiect, 'BLOCAT (NUME)');
            RAISE_APPLICATION_ERROR(-20007, 'EROARE: Numele tabelului trebuie sa se termine in _F1!');
        END IF;
    END IF;

    IF eveniment = 'DROP' AND tip_obiect = 'TABLE' THEN
        IF UPPER(nume_obiect) LIKE '%_F1' THEN
            logheaza_eveniment_ldd(utilizator, eveniment, tip_obiect, nume_obiect, 'BLOCAT (DROP)');
            RAISE_APPLICATION_ERROR(-20008, 'SECURITATE: Stergerea tabelelor oficiale F1 este interzisa!');
        END IF;
    END IF;

    logheaza_eveniment_ldd(utilizator, eveniment, tip_obiect, nume_obiect, 'REUSIT');
END;

-- 13

CREATE OR REPLACE PACKAGE PKG_ANALIZA_PILOT IS
    TYPE info_cursa_rec IS RECORD (
        id_cursa       CURSA_F1.id_cursa%TYPE,
        tip_cursa      CURSA_F1.tip_cursa%TYPE,
        data_cursa     CURSA_F1.data_cursa%TYPE,
        pozitie_finala PILOT_CURSA_F1.pozitie_finala%TYPE
    );

    TYPE lista_curse_tab IS TABLE OF info_cursa_rec INDEX BY PLS_INTEGER;

    FUNCTION nr_curse_pilot (identificator_pilot IN PILOT_F1.id_pilot%TYPE, an_sezon IN NUMBER) 
    RETURN NUMBER;

    FUNCTION pozitie_medie_pilot (identificator_pilot IN PILOT_F1.id_pilot%TYPE, an_sezon IN NUMBER) 
    RETURN NUMBER;

    PROCEDURE incarca_curse_pilot (identificator_pilot IN PILOT_F1.id_pilot%TYPE, an_sezon IN NUMBER, colectie_curse OUT lista_curse_tab);

    PROCEDURE raport_pilot_sezon (identificator_pilot IN PILOT_F1.id_pilot%TYPE, an_sezon IN NUMBER);

END PKG_ANALIZA_PILOT;

CREATE OR REPLACE PACKAGE BODY PKG_ANALIZA_PILOT IS

    FUNCTION nr_curse_pilot (identificator_pilot IN PILOT_F1.id_pilot%TYPE, an_sezon IN NUMBER) 
    RETURN NUMBER 
    IS
        numar_total NUMBER;
    BEGIN
        SELECT COUNT(*) INTO numar_total 
        FROM PILOT_CURSA_F1 PC
        JOIN CURSA_F1 C ON PC.id_cursa = C.id_cursa
        WHERE PC.id_pilot = identificator_pilot AND EXTRACT(YEAR FROM C.data_cursa) = an_sezon;

        RETURN numar_total;
    END nr_curse_pilot;

    FUNCTION pozitie_medie_pilot (identificator_pilot IN PILOT_F1.id_pilot%TYPE, an_sezon IN NUMBER) 
    RETURN NUMBER 
    IS
        valoare_medie NUMBER;
    BEGIN
        SELECT AVG(pc.pozitie_finala) INTO valoare_medie
        FROM PILOT_CURSA_F1 pc
        JOIN CURSA_F1 c ON PC.id_cursa = C.id_cursa
        WHERE PC.id_pilot = identificator_pilot AND EXTRACT(YEAR FROM C.data_cursa) = an_sezon;

        RETURN valoare_medie;
    END pozitie_medie_pilot;

    PROCEDURE incarca_curse_pilot (identificator_pilot IN PILOT_F1.id_pilot%TYPE, an_sezon IN NUMBER, colectie_curse OUT lista_curse_tab)
    IS
        contor NUMBER := 0;
    BEGIN
        FOR r_cursa IN (
            SELECT C.id_cursa, C.tip_cursa, C.data_cursa, PC.pozitie_finala 
            FROM PILOT_CURSA_F1 PC
            JOIN CURSA_F1 C ON PC.id_cursa = C.id_cursa
            WHERE PC.id_pilot = identificator_pilot AND EXTRACT(YEAR FROM C.data_cursa) = an_sezon
            ORDER BY C.data_cursa
        )
        LOOP
            contor := contor + 1;
            colectie_curse(contor).id_cursa := r_cursa.id_cursa;
            colectie_curse(contor).tip_cursa := r_cursa.tip_cursa;
            colectie_curse(contor).data_cursa := r_cursa.data_cursa;
            colectie_curse(contor).pozitie_finala := r_cursa.pozitie_finala;
        END LOOP;
    END incarca_curse_pilot;

    PROCEDURE raport_pilot_sezon (identificator_pilot IN PILOT_F1.id_pilot%TYPE, an_sezon IN NUMBER) 
    IS
        tabel_curse   lista_curse_tab;
        numar_curse   NUMBER;
        medie_pozitie NUMBER;
        nume_pilot    VARCHAR2(100);
    BEGIN
        SELECT nume || ' ' || prenume INTO nume_pilot 
        FROM PILOT_F1 
        WHERE id_pilot = identificator_pilot;

        incarca_curse_pilot(identificator_pilot, an_sezon, tabel_curse);
        numar_curse   := nr_curse_pilot(identificator_pilot, an_sezon);
        medie_pozitie := pozitie_medie_pilot(identificator_pilot, an_sezon);

        DBMS_OUTPUT.PUT_LINE('====================================================');
        DBMS_OUTPUT.PUT_LINE('RAPORT SEZON: ' || an_sezon);
        DBMS_OUTPUT.PUT_LINE('PILOT: ' || nume_pilot || ' (ID: ' || identificator_pilot || ')');
        DBMS_OUTPUT.PUT_LINE('----------------------------------------------------');
        DBMS_OUTPUT.PUT_LINE('Total curse participat: ' || numar_curse);
        DBMS_OUTPUT.PUT_LINE('Pozitie medie obtinuta: ' || ROUND(NVL(medie_pozitie, 0), 2));
        DBMS_OUTPUT.PUT_LINE('----------------------------------------------------');

        IF tabel_curse.COUNT > 0 THEN
            FOR i IN tabel_curse.FIRST .. tabel_curse.LAST LOOP
                DBMS_OUTPUT.PUT_LINE('Cursa ID: ' || tabel_curse(i).id_cursa || ' | Tip: ' || RPAD(tabel_curse(i).tip_cursa, 12) || ' | Data: ' || TO_CHAR(tabel_curse(i).data_cursa, 'DD-MM-YYYY') || ' | Pozitie: ' || tabel_curse(i).pozitie_finala);
            END LOOP;
        ELSE
            DBMS_OUTPUT.PUT_LINE('Nu exista participari inregistrate in acest an.');
        END IF;
        DBMS_OUTPUT.PUT_LINE('====================================================');
    END raport_pilot_sezon;

END PKG_ANALIZA_PILOT;


BEGIN
    PKG_ANALIZA_PILOT.raport_pilot_sezon(1, 2025);
END;



 
